///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using System.IO;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATS_Supplier_Portal_Test
{
    public partial class ExportImportShipmentsPROD
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void DeleteFileifExistsShipmentExport()
        {
            string pathShipment = @"\\ca01a9001\pgmis\Deployment_DEV\Ranorex\Supplier_Portal\PROD\ExportShipment\ConfirmShipment.xlsx";
            if(File.Exists(pathShipment))
        	{
        		Report.Info("Deleting file: " + pathShipment);
        		File.Delete(pathShipment);
        	}
        	else
        	{
        		Report.Info("File not found: " + pathShipment);
        	}
        }

    }
}
