///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitSingleQuote recording.
    /// </summary>
    [TestModule("a4847951-52fa-4794-904e-c0fa35e9aaaf", ModuleType.Recording, 1)]
    public partial class SubmitSingleQuote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SubmitSingleQuote instance = new SubmitSingleQuote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitSingleQuote()
        {
            varRFQNumber = "";
            varRandom = "";
            varNumEntries = "";
            varShippingMethodText = "OCN - Ocean";
            varRequestedShipDate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitSingleQuote Instance
        {
            get { return instance; }
        }

#region Variables

        string _varRandom;

        /// <summary>
        /// Gets or sets the value of variable varRandom.
        /// </summary>
        [TestVariable("575d66ca-5e8a-4680-ab45-c58b904f802a")]
        public string varRandom
        {
            get { return _varRandom; }
            set { _varRandom = value; }
        }

        string _varNumEntries;

        /// <summary>
        /// Gets or sets the value of variable varNumEntries.
        /// </summary>
        [TestVariable("ea60c1a7-5404-4d73-800d-2d3f4e3702e1")]
        public string varNumEntries
        {
            get { return _varNumEntries; }
            set { _varNumEntries = value; }
        }

        string _varShippingMethodText;

        /// <summary>
        /// Gets or sets the value of variable varShippingMethodText.
        /// </summary>
        [TestVariable("ad332c54-7e31-4ebb-bc1f-bbf1113f4993")]
        public string varShippingMethodText
        {
            get { return _varShippingMethodText; }
            set { _varShippingMethodText = value; }
        }

        string _varRequestedShipDate;

        /// <summary>
        /// Gets or sets the value of variable varRequestedShipDate.
        /// </summary>
        [TestVariable("ba7e8bda-da23-4912-864c-de3c4536b514")]
        public string varRequestedShipDate
        {
            get { return _varRequestedShipDate; }
            set { _varRequestedShipDate = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("eca981c8-50cc-446e-bd6b-25e5f2c4423e")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varDetailPrice.
        /// </summary>
        [TestVariable("66b92e19-5faf-4d0e-a0b1-36e7d2570648")]
        public string varDetailPrice
        {
            get { return repo.varDetailPrice; }
            set { repo.varDetailPrice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(0));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(1));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'LoginATSSupplierPortal.Search1'", repo.LoginATSSupplierPortal.Search1Info, new ActionTimeout(300000), new RecordItemIndex(3));
            repo.LoginATSSupplierPortal.Search1Info.WaitForExists(300000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to not exist. Associated repository item: 'RFQListingATSSupplierPortal.Loading'", repo.RFQListingATSSupplierPortal.LoadingInfo, new ActionTimeout(180000), new RecordItemIndex(4));
            repo.RFQListingATSSupplierPortal.LoadingInfo.WaitForNotExists(180000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Search' at Center.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(6));
            repo.LoginATSSupplierPortal.Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(7));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRFQNumber' with focus on 'LoginATSSupplierPortal.Search'.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(8));
            repo.LoginATSSupplierPortal.Search.PressKeys(varRFQNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.SelectRFQNumber' at Center.", repo.LoginATSSupplierPortal.SelectRFQNumberInfo, new RecordItemIndex(9));
            repo.LoginATSSupplierPortal.SelectRFQNumber.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'LoginATSSupplierPortal.BtnSetPromise'", repo.LoginATSSupplierPortal.BtnSetPromiseInfo, new ActionTimeout(10000), new RecordItemIndex(10));
            repo.LoginATSSupplierPortal.BtnSetPromiseInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'LoginATSSupplierPortal.DetailsTableInfo' and assigning the part of its value captured by '\\d+(?!.*\\d+)' to variable 'varNumEntries'.", repo.LoginATSSupplierPortal.DetailsTableInfoInfo, new RecordItemIndex(11));
            varNumEntries = repo.LoginATSSupplierPortal.DetailsTableInfo.Element.GetAttributeValueText("InnerText", new Regex("\\d+(?!.*\\d+)"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'TagValue' from item 'LoginATSSupplierPortal.RequestedShipDate' and assigning its value to variable 'varRequestedShipDate'.", repo.LoginATSSupplierPortal.RequestedShipDateInfo, new RecordItemIndex(12));
            varRequestedShipDate = repo.LoginATSSupplierPortal.RequestedShipDate.Element.GetAttributeValueText("TagValue");
            Delay.Milliseconds(0);
            
            ExpandRFQInfo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(14));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RFQListingATSSupplierPortal.PromiseDateText' at Center.", repo.RFQListingATSSupplierPortal.PromiseDateTextInfo, new RecordItemIndex(15));
            repo.RFQListingATSSupplierPortal.PromiseDateText.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Right}{Right}{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(16));
            Keyboard.Press("{Right}{Right}{Right}{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnExport' at Center.", repo.LoginATSSupplierPortal.BtnExportInfo, new RecordItemIndex(17));
            repo.LoginATSSupplierPortal.BtnExport.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VendorQuoteATSSupplierPortalInt.Options' at Center.", repo.VendorQuoteATSSupplierPortalInt.OptionsInfo, new RecordItemIndex(18));
            //repo.VendorQuoteATSSupplierPortalInt.Options.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Iexplore.SaveAs' at Center.", repo.Iexplore.SaveAsInfo, new RecordItemIndex(19));
            //repo.Iexplore.SaveAs.MoveTo();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Iexplore.SaveAs' at Center.", repo.Iexplore.SaveAsInfo, new RecordItemIndex(20));
            //repo.Iexplore.SaveAs.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(21));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(22));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}'.", new RecordItemIndex(23));
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\Web\\QuoteExport\\ShippingDate.xlsx'.", new RecordItemIndex(24));
            Keyboard.Press("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\Web\\QuoteExport\\ShippingDate.xlsx");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\Web\\QuoteExport\\ShippingDate.xlsx' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(25));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\Web\\QuoteExport\\ShippingDate.xlsx");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(26));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at Center.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(27));
            repo.SaveAs.ButtonSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmSaveAs.ButtonYes' at Center.", repo.ConfirmSaveAs.ButtonYesInfo, new RecordItemIndex(28));
            repo.ConfirmSaveAs.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            Delay.Duration(1000, false);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Move item 'VendorQuoteATSSupplierPortalInt.Close' at Center.", repo.VendorQuoteATSSupplierPortalInt.CloseInfo, new RecordItemIndex(30));
                //repo.VendorQuoteATSSupplierPortalInt.Close.MoveTo();
                //Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(30)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'VendorQuoteATSSupplierPortalInt.Close' at Center.", repo.VendorQuoteATSSupplierPortalInt.CloseInfo, new RecordItemIndex(31));
                //repo.VendorQuoteATSSupplierPortalInt.Close.Click();
                //Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(31)); }
            
            SPCollection.ValidateExcelContainsShippingDate("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\Web\\QuoteExport\\ShippingDate.xlsx", "test", "G", "2", varRequestedShipDate);
            Delay.Milliseconds(0);
            
            ValidateRequestedShipDate(varRequestedShipDate);
            Delay.Milliseconds(0);
            
            ClickPromiseDate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.DetailPrice' at Center.", repo.LoginATSSupplierPortal.DetailPriceInfo, new RecordItemIndex(35));
            repo.LoginATSSupplierPortal.DetailPrice.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}' with focus on 'LoginATSSupplierPortal.DetailPrice'.", repo.LoginATSSupplierPortal.DetailPriceInfo, new RecordItemIndex(36));
            repo.LoginATSSupplierPortal.DetailPrice.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(37));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2.05' with focus on 'LoginATSSupplierPortal.DetailPrice'.", repo.LoginATSSupplierPortal.DetailPriceInfo, new RecordItemIndex(38));
            repo.LoginATSSupplierPortal.DetailPrice.PressKeys("2.05");
            Delay.Milliseconds(0);
            
            varRandom = SPCollection.RandomString(ValueConverter.ArgumentFromString<int>("length", "8"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.QuoteNumber' at Center.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(40));
            repo.LoginATSSupplierPortal.QuoteNumber.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varRandom' on item 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(41));
            //repo.LoginATSSupplierPortal.QuoteNumber.Element.SetAttributeValue("InnerText", varRandom);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRandom' with focus on 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(42));
            repo.LoginATSSupplierPortal.QuoteNumber.PressKeys(varRandom);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'dsfwe' with focus on 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(43));
            repo.LoginATSSupplierPortal.QuoteNumber.PressKeys("dsfwe");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(44));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RFQListingATSSupplierPortal.PromiseDateText' at Center.", repo.RFQListingATSSupplierPortal.PromiseDateTextInfo, new RecordItemIndex(45));
            repo.RFQListingATSSupplierPortal.PromiseDateText.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Right}{Right}{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(46));
            Keyboard.Press("{Right}{Right}{Right}{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSave' at Center.", repo.LoginATSSupplierPortal.BtnSaveInfo, new RecordItemIndex(47));
            repo.LoginATSSupplierPortal.BtnSave.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking PerformClick() on item 'LoginATSSupplierPortal.BtnSave'.", repo.LoginATSSupplierPortal.BtnSaveInfo, new RecordItemIndex(48));
            repo.LoginATSSupplierPortal.BtnSave.PerformClick();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(49));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(50));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(51));
            repo.LoginATSSupplierPortal.BtnSubmit.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(52));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(53));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}'.", new RecordItemIndex(54));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(55));
            repo.LoginATSSupplierPortal.BtnSubmit.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(56));
            repo.LoginATSSupplierPortal.BtnSubmit.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(57));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.LoginATSSupplierPortal.Self, false, new RecordItemIndex(58));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
