///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATS_Supplier_Portal_Test
{
    public partial class CheckSupplierPortalForReqNumber
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void CheckForUserReferenceinSP(string reqNum, string SPEnvironmentServer, int timeoutMinutes)
        {
        	int totalTimeout = timeoutMinutes * 2;
        	int i = 0;
        	do
        	{      		
        		Report.Info("Did not find User Reference Number in Supplier Portal, retrying in 30 seconds");
        		Delay.Seconds(30);   			
        		i++;
        	}while ((SPCollection.SQLCheckSPForReqNumber(reqNum,SPEnvironmentServer)<1) && i<totalTimeout);
        	
        	if(i>=totalTimeout)
        	{
        		Report.Error("Could not find User Reference in Supplier Portal Server: " + SPEnvironmentServer + " after " + timeoutMinutes + " minutes, the check timed out.");
        		Ranorex.Validate.Fail();
        	}
        	
        	Delay.Seconds(30);
        }

    }
}
