///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateRFQPROD recording.
    /// </summary>
    [TestModule("abb27670-1df4-481c-af41-f4d36ebc0577", ModuleType.Recording, 1)]
    public partial class CreateRFQPROD : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static CreateRFQPROD instance = new CreateRFQPROD();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateRFQPROD()
        {
            varUserReferenceNumber = "";
            varRFQNumber = "";
            varUsername = "";
            varLineNo = "";
            varShippingMethodText = "";
            varDateIncorrect = "";
            varcolumnIndex = "";
            varDate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateRFQPROD Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUserReferenceNumber;

        /// <summary>
        /// Gets or sets the value of variable varUserReferenceNumber.
        /// </summary>
        [TestVariable("3463279b-5235-40a5-86be-9a7b6974b71c")]
        public string varUserReferenceNumber
        {
            get { return _varUserReferenceNumber; }
            set { _varUserReferenceNumber = value; }
        }

        string _varLineNo;

        /// <summary>
        /// Gets or sets the value of variable varLineNo.
        /// </summary>
        [TestVariable("f92c5b88-cccc-4e23-ae2c-946bfa7bab38")]
        public string varLineNo
        {
            get { return _varLineNo; }
            set { _varLineNo = value; }
        }

        string _varShippingMethodText;

        /// <summary>
        /// Gets or sets the value of variable varShippingMethodText.
        /// </summary>
        [TestVariable("ca9ec716-30db-4bb6-a89c-b32aad863c4a")]
        public string varShippingMethodText
        {
            get { return _varShippingMethodText; }
            set { _varShippingMethodText = value; }
        }

        string _varDateIncorrect;

        /// <summary>
        /// Gets or sets the value of variable varDateIncorrect.
        /// </summary>
        [TestVariable("30b44620-d087-4520-b5ab-6ef8dbc4f4dd")]
        public string varDateIncorrect
        {
            get { return _varDateIncorrect; }
            set { _varDateIncorrect = value; }
        }

        string _varDate;

        /// <summary>
        /// Gets or sets the value of variable varDate.
        /// </summary>
        [TestVariable("dc360c2f-ab29-4f4f-a092-c4e732fb5280")]
        public string varDate
        {
            get { return _varDate; }
            set { _varDate = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varcolumnIndex.
        /// </summary>
        [TestVariable("ff43468f-a3e1-443a-9175-4b1b22b0b0b3")]
        public string varcolumnIndex
        {
            get { return repo.varcolumnIndex; }
            set { repo.varcolumnIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("8745a66f-f9a5-48c3-b229-36221a15bc99")]
        public string varUsername
        {
            get { return repo.varUsername; }
            set { repo.varUsername = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("c3ce622b-58dd-4233-8d75-3116fe65b331")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQ' at Center.", repo.MainWindow.NavigationPanel.CreateRFQInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.CreateRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.VendorRequirements' at Center.", repo.MainWindow.NavigationPanel.VendorRequirementsInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.VendorRequirements.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(4));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SupplierPortalContactDropDown' at Center.", repo.MainWindow.NavigationPanel.SupplierPortalContactDropDownInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.SupplierPortalContactDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.RanorexRT' at Center.", repo.ATSSupplierPortalManagment.RanorexRTInfo, new RecordItemIndex(6));
            repo.ATSSupplierPortalManagment.RanorexRT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SupplierPortalContactBackupDropDown' at Center.", repo.MainWindow.NavigationPanel.SupplierPortalContactBackupDropDownInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.SupplierPortalContactBackupDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.RanorexRT' at Center.", repo.ATSSupplierPortalManagment.RanorexRTInfo, new RecordItemIndex(8));
            repo.ATSSupplierPortalManagment.RanorexRT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.EngineeringContactDropDown' at Center.", repo.MainWindow.NavigationPanel.EngineeringContactDropDownInfo, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.EngineeringContactDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.RanorexRT' at Center.", repo.ATSSupplierPortalManagment.RanorexRTInfo, new RecordItemIndex(10));
            repo.ATSSupplierPortalManagment.RanorexRT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.EngineeringContactBackupDropDown' at Center.", repo.MainWindow.NavigationPanel.EngineeringContactBackupDropDownInfo, new RecordItemIndex(11));
            repo.MainWindow.NavigationPanel.EngineeringContactBackupDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.RanorexRT' at Center.", repo.ATSSupplierPortalManagment.RanorexRTInfo, new RecordItemIndex(12));
            repo.ATSSupplierPortalManagment.RanorexRT.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ShippingMethodComboBox' at Center.", repo.MainWindow.NavigationPanel.ShippingMethodComboBoxInfo, new RecordItemIndex(13));
            repo.MainWindow.NavigationPanel.ShippingMethodComboBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.OCNOcean' at Center.", repo.ATSSupplierPortalManagment.OCNOceanInfo, new RecordItemIndex(14));
            repo.ATSSupplierPortalManagment.OCNOcean.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.ShippingMethodComboBoxText' and assigning its value to variable 'varShippingMethodText'.", repo.MainWindow.NavigationPanel.ShippingMethodComboBoxTextInfo, new RecordItemIndex(15));
            varShippingMethodText = repo.MainWindow.NavigationPanel.ShippingMethodComboBoxText.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varShippingMethodText, new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.VendorSelection' at Center.", repo.MainWindow.NavigationPanel.VendorSelectionInfo, new RecordItemIndex(17));
            repo.MainWindow.NavigationPanel.VendorSelection.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(18));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ATSAUTOMATION1' at Center.", repo.MainWindow.NavigationPanel.ATSAUTOMATION1Info, new RecordItemIndex(19));
            repo.MainWindow.NavigationPanel.ATSAUTOMATION1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.NavigationPanel.ATSAUTOMATION11'.", repo.MainWindow.NavigationPanel.ATSAUTOMATION11Info, new RecordItemIndex(20));
            Validate.Exists(repo.MainWindow.NavigationPanel.ATSAUTOMATION11Info);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailsInBatch' at Center.", repo.MainWindow.NavigationPanel.DetailsInBatchInfo, new RecordItemIndex(21));
            repo.MainWindow.NavigationPanel.DetailsInBatch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(22));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            varUserReferenceNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RequisitionNumber\\req.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varUserReferenceNumber' on item 'MainWindow.NavigationPanel.UserReferenceFilter'.", repo.MainWindow.NavigationPanel.UserReferenceFilterInfo, new RecordItemIndex(24));
            repo.MainWindow.NavigationPanel.UserReferenceFilter.Element.SetAttributeValue("Text", varUserReferenceNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(25));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CheckBoxItem1' at Center.", repo.MainWindow.NavigationPanel.CheckBoxItem1Info, new RecordItemIndex(26));
            repo.MainWindow.NavigationPanel.CheckBoxItem1.Click();
            Delay.Milliseconds(200);
            
            varDateIncorrect = SPCollection.GetDateTimePlusXDays(ValueConverter.ArgumentFromString<int>("days", "30"));
            Delay.Milliseconds(0);
            
            varcolumnIndex = ValueConverter.ToString(SPCollection.GetColumnIndexofHeader("Required Date"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(29));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.Element.SetAttributeValue("Text", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox' at Center.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(30));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varDateIncorrect' with focus on 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(31));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.PressKeys(varDateIncorrect);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varDateIncorrect) on item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(32));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, "Text", varDateIncorrect);
            Delay.Milliseconds(0);
            
            //SPCollection.SelectHalfofCheckboxes();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQButton' at Center.", repo.MainWindow.NavigationPanel.CreateRFQButtonInfo, new RecordItemIndex(34));
            repo.MainWindow.NavigationPanel.CreateRFQButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'NotificationsWindow.ErrorShippingDate'", repo.NotificationsWindow.ErrorShippingDateInfo, new ActionTimeout(60000), new RecordItemIndex(35));
            repo.NotificationsWindow.ErrorShippingDateInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NotificationsWindow.ErrorShippingDate'.", repo.NotificationsWindow.ErrorShippingDateInfo, new RecordItemIndex(36));
            Validate.Exists(repo.NotificationsWindow.ErrorShippingDateInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(37));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotificationsWindow.CloseButton' at Center.", repo.NotificationsWindow.CloseButtonInfo, new RecordItemIndex(38));
            repo.NotificationsWindow.CloseButton.Click();
            Delay.Milliseconds(200);
            
            varDate = SPCollection.GetDateTimePlusXDays(ValueConverter.ArgumentFromString<int>("days", "365"));
            Delay.Milliseconds(0);
            
            varcolumnIndex = ValueConverter.ToString(SPCollection.GetColumnIndexofHeader("Required Date"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(41));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.Element.SetAttributeValue("Text", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox' at Center.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(42));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varDate' with focus on 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(43));
            repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBox.PressKeys(varDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varDate) on item 'MainWindow.NavigationPanel.ReqDateFirstRowTextBox'.", repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, new RecordItemIndex(44));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.ReqDateFirstRowTextBoxInfo, "Text", varDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(45));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(46));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.CellLineNumber0' and assigning its value to variable 'varLineNo'.", repo.MainWindow.NavigationPanel.CellLineNumber0Info, new RecordItemIndex(47));
            varLineNo = repo.MainWindow.NavigationPanel.CellLineNumber0.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.UnprocessedDetailsGrid, false, new RecordItemIndex(48));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.FileAttachments' at Center.", repo.MainWindow.NavigationPanel.FileAttachmentsInfo, new RecordItemIndex(49));
            repo.MainWindow.NavigationPanel.FileAttachments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(50));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.AddFileButton' at Center.", repo.MainWindow.NavigationPanel.AddFileButtonInfo, new RecordItemIndex(51));
            repo.MainWindow.NavigationPanel.AddFileButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Attachment.pdf' on item 'Open.Text1148'.", repo.Open.Text1148Info, new RecordItemIndex(52));
            repo.Open.Text1148.Element.SetAttributeValue("Text", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Attachment.pdf");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at Center.", repo.Open.ButtonOpenInfo, new RecordItemIndex(53));
            repo.Open.ButtonOpen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(54));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQButton' at Center.", repo.MainWindow.NavigationPanel.CreateRFQButtonInfo, new RecordItemIndex(55));
            repo.MainWindow.NavigationPanel.CreateRFQButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'NotificationsWindow.SuccessMessage'", repo.NotificationsWindow.SuccessMessageInfo, new ActionTimeout(60000), new RecordItemIndex(56));
            repo.NotificationsWindow.SuccessMessageInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NotificationsWindow.SuccessMessage'.", repo.NotificationsWindow.SuccessMessageInfo, new RecordItemIndex(57));
            Validate.Exists(repo.NotificationsWindow.SuccessMessageInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'NotificationsWindow.SuccessMessage' and assigning the part of its value captured by '\\d+' to variable 'varRFQNumber'.", repo.NotificationsWindow.SuccessMessageInfo, new RecordItemIndex(58));
            varRFQNumber = repo.NotificationsWindow.SuccessMessage.Element.GetAttributeValueText("Text", new Regex("\\d+"));
            Delay.Milliseconds(0);
            
            SPCollection.WriteReqNumber(varRFQNumber, "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RFQNumber\\RFQNumber.txt");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NotificationsWindow.SuccessMessage, false, new RecordItemIndex(60));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(61));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotificationsWindow.CloseButton' at Center.", repo.NotificationsWindow.CloseButtonInfo, new RecordItemIndex(62));
            repo.NotificationsWindow.CloseButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ProcessRFQButton' at Center.", repo.MainWindow.NavigationPanel.ProcessRFQButtonInfo, new RecordItemIndex(63));
            repo.MainWindow.NavigationPanel.ProcessRFQButton.Click();
            Delay.Milliseconds(200);
            
            varUsername = SPCollection.GetUsername();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(65));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailViewDropDown' at Center.", repo.MainWindow.NavigationPanel.DetailViewDropDownInfo, new RecordItemIndex(66));
            repo.MainWindow.NavigationPanel.DetailViewDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.username' at Center.", repo.ATSSupplierPortalManagment.usernameInfo, new RecordItemIndex(67));
            repo.ATSSupplierPortalManagment.username.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SelectRFQ' at Center.", repo.MainWindow.NavigationPanel.SelectRFQInfo, new RecordItemIndex(68));
            repo.MainWindow.NavigationPanel.SelectRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(69));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Details' at Center.", repo.MainWindow.NavigationPanel.DetailsInfo, new RecordItemIndex(70));
            repo.MainWindow.NavigationPanel.Details.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.TableProcessGrid, false, new RecordItemIndex(71));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
