///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FilterDetailsProcessRFQ recording.
    /// </summary>
    [TestModule("ce5dcba9-9a34-43c2-93cb-aaff21ef3d88", ModuleType.Recording, 1)]
    public partial class FilterDetailsProcessRFQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static FilterDetailsProcessRFQ instance = new FilterDetailsProcessRFQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FilterDetailsProcessRFQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FilterDetailsProcessRFQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Details' at Center.", repo.MainWindow.NavigationPanel.DetailsInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.Details.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailFilterProcessRFQ' at Center.", repo.MainWindow.NavigationPanel.DetailFilterProcessRFQInfo, new RecordItemIndex(1));
            repo.MainWindow.NavigationPanel.DetailFilterProcessRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '13605' with focus on 'MainWindow.NavigationPanel.DetailFilterProcessRFQ'.", repo.MainWindow.NavigationPanel.DetailFilterProcessRFQInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.DetailFilterProcessRFQ.PressKeys("13605");
            Delay.Milliseconds(0);
            
            SPCollection.FilterValidateTable("Detail", "13605", ValueConverter.ArgumentFromString<bool>("compareComboBox", "False"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextClearAllFilters1' at Center.", repo.MainWindow.NavigationPanel.TextClearAllFilters1Info, new RecordItemIndex(4));
            repo.MainWindow.NavigationPanel.TextClearAllFilters1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'MainWindow.NavigationPanel.DetailFilterProcessRFQ'.", repo.MainWindow.NavigationPanel.DetailFilterProcessRFQInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.DetailFilterProcessRFQInfo, "Text", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.RevisionFilter' at Center.", repo.MainWindow.NavigationPanel.RevisionFilterInfo, new RecordItemIndex(6));
            repo.MainWindow.NavigationPanel.RevisionFilter.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'A' with focus on 'MainWindow.NavigationPanel.RevisionFilter'.", repo.MainWindow.NavigationPanel.RevisionFilterInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.RevisionFilter.PressKeys("A");
            Delay.Milliseconds(0);
            
            SPCollection.FilterValidateTable("Revision", "A", ValueConverter.ArgumentFromString<bool>("compareComboBox", "False"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextClearAllFilters1' at Center.", repo.MainWindow.NavigationPanel.TextClearAllFilters1Info, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.TextClearAllFilters1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'MainWindow.NavigationPanel.RevisionFilter'.", repo.MainWindow.NavigationPanel.RevisionFilterInfo, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.RevisionFilterInfo, "Text", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DescriptionFilter1' at Center.", repo.MainWindow.NavigationPanel.DescriptionFilter1Info, new RecordItemIndex(11));
            repo.MainWindow.NavigationPanel.DescriptionFilter1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'plate' with focus on 'MainWindow.NavigationPanel.DescriptionFilter1'.", repo.MainWindow.NavigationPanel.DescriptionFilter1Info, new RecordItemIndex(12));
            repo.MainWindow.NavigationPanel.DescriptionFilter1.PressKeys("plate");
            Delay.Milliseconds(0);
            
            SPCollection.FilterValidateTable("Description", "PLATE", ValueConverter.ArgumentFromString<bool>("compareComboBox", "False"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextClearAllFilters1' at Center.", repo.MainWindow.NavigationPanel.TextClearAllFilters1Info, new RecordItemIndex(14));
            repo.MainWindow.NavigationPanel.TextClearAllFilters1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'MainWindow.NavigationPanel.DescriptionFilter1'.", repo.MainWindow.NavigationPanel.DescriptionFilter1Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.DescriptionFilter1Info, "Text", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.QtyFilter1' at Center.", repo.MainWindow.NavigationPanel.QtyFilter1Info, new RecordItemIndex(16));
            repo.MainWindow.NavigationPanel.QtyFilter1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'MainWindow.NavigationPanel.QtyFilter1'.", repo.MainWindow.NavigationPanel.QtyFilter1Info, new RecordItemIndex(17));
            repo.MainWindow.NavigationPanel.QtyFilter1.PressKeys("1");
            Delay.Milliseconds(0);
            
            SPCollection.FilterValidateTable("Qty", "1", ValueConverter.ArgumentFromString<bool>("compareComboBox", "False"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextClearAllFilters1' at Center.", repo.MainWindow.NavigationPanel.TextClearAllFilters1Info, new RecordItemIndex(19));
            repo.MainWindow.NavigationPanel.TextClearAllFilters1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'MainWindow.NavigationPanel.QtyFilter1'.", repo.MainWindow.NavigationPanel.QtyFilter1Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.QtyFilter1Info, "Text", (string)null);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'MainWindow.NavigationPanel.KittingFilter1'.", repo.MainWindow.NavigationPanel.KittingFilter1Info, new RecordItemIndex(21));
            repo.MainWindow.NavigationPanel.KittingFilter1.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '13605' on item 'MainWindow.NavigationPanel.KittingFilter1'.", repo.MainWindow.NavigationPanel.KittingFilter1Info, new RecordItemIndex(22));
            repo.MainWindow.NavigationPanel.KittingFilter1.Element.SetAttributeValue("Text", "13605");
            Delay.Milliseconds(0);
            
            SPCollection.FilterValidateTable("Kitting", "13605", ValueConverter.ArgumentFromString<bool>("compareComboBox", "False"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextClearAllFilters1' at Center.", repo.MainWindow.NavigationPanel.TextClearAllFilters1Info, new RecordItemIndex(24));
            repo.MainWindow.NavigationPanel.TextClearAllFilters1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='(null)') on item 'MainWindow.NavigationPanel.KittingFilter1'.", repo.MainWindow.NavigationPanel.KittingFilter1Info, new RecordItemIndex(25));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.KittingFilter1Info, "Text", (string)null);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
