///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The GetUserReferencePROD recording.
    /// </summary>
    [TestModule("57e110d6-36ba-4be4-a528-799e12889d6d", ModuleType.Recording, 1)]
    public partial class GetUserReferencePROD : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static GetUserReferencePROD instance = new GetUserReferencePROD();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public GetUserReferencePROD()
        {
            varUserReferenceNumber = "";
            varQty = "";
            varUsername = "";
            varUserReference0 = "";
            varLineNo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static GetUserReferencePROD Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUserReferenceNumber;

        /// <summary>
        /// Gets or sets the value of variable varUserReferenceNumber.
        /// </summary>
        [TestVariable("62a3db35-60e7-4af1-881f-2d7343818857")]
        public string varUserReferenceNumber
        {
            get { return _varUserReferenceNumber; }
            set { _varUserReferenceNumber = value; }
        }

        string _varQty;

        /// <summary>
        /// Gets or sets the value of variable varQty.
        /// </summary>
        [TestVariable("0a32bbc8-1047-4de5-b480-78bffad42b2b")]
        public string varQty
        {
            get { return _varQty; }
            set { _varQty = value; }
        }

        string _varUserReference0;

        /// <summary>
        /// Gets or sets the value of variable varUserReference0.
        /// </summary>
        [TestVariable("92f07d06-4033-442f-b6bf-6efe1f09a4b3")]
        public string varUserReference0
        {
            get { return _varUserReference0; }
            set { _varUserReference0 = value; }
        }

        string _varLineNo;

        /// <summary>
        /// Gets or sets the value of variable varLineNo.
        /// </summary>
        [TestVariable("693fc468-6535-4abe-8a5a-f2fdacd5bb97")]
        public string varLineNo
        {
            get { return _varLineNo; }
            set { _varLineNo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varUsername.
        /// </summary>
        [TestVariable("80341791-5cdc-4c8c-9a4f-824fb5a4bbd3")]
        public string varUsername
        {
            get { return repo.varUsername; }
            set { repo.varUsername = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQ' at Center.", repo.MainWindow.NavigationPanel.CreateRFQInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.CreateRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailsInBatch' at Center.", repo.MainWindow.NavigationPanel.DetailsInBatchInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.DetailsInBatch.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '90000000' on item 'MainWindow.NavigationPanel.UserReferenceFilter'.", repo.MainWindow.NavigationPanel.UserReferenceFilterInfo, new RecordItemIndex(3));
            //repo.MainWindow.NavigationPanel.UserReferenceFilter.Element.SetAttributeValue("Text", "90000000");
            //Delay.Milliseconds(0);
            
            varUserReferenceNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RequisitionNumber\\req.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varUserReferenceNumber' on item 'MainWindow.NavigationPanel.UserReferenceFilter'.", repo.MainWindow.NavigationPanel.UserReferenceFilterInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.UserReferenceFilter.Element.SetAttributeValue("Text", varUserReferenceNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Detail' at Center.", repo.MainWindow.NavigationPanel.DetailInfo, new RecordItemIndex(6));
            repo.MainWindow.NavigationPanel.Detail.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.QuantityRow0' and assigning its value to variable 'varQty'.", repo.MainWindow.NavigationPanel.QuantityRow0Info, new RecordItemIndex(7));
            varQty = repo.MainWindow.NavigationPanel.QuantityRow0.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            varUsername = SPCollection.GetUsername();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.AssigneeDropDownRow0' at Center.", repo.MainWindow.NavigationPanel.AssigneeDropDownRow0Info, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.AssigneeDropDownRow0.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.AssigneeList.ranorexrt' at Center.", repo.ATSSupplierPortalManagment.AssigneeList.ranorexrtInfo, new RecordItemIndex(10));
            repo.ATSSupplierPortalManagment.AssigneeList.ranorexrt.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CopyButton0' at Center.", repo.MainWindow.NavigationPanel.CopyButton0Info, new RecordItemIndex(11));
            repo.MainWindow.NavigationPanel.CopyButton0.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(12));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(13));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.CellUserReference0' and assigning its value to variable 'varUserReference0'.", repo.MainWindow.NavigationPanel.CellUserReference0Info, new RecordItemIndex(14));
            varUserReference0 = repo.MainWindow.NavigationPanel.CellUserReference0.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.CellLineNumber0' and assigning its value to variable 'varLineNo'.", repo.MainWindow.NavigationPanel.CellLineNumber0Info, new RecordItemIndex(15));
            varLineNo = repo.MainWindow.NavigationPanel.CellLineNumber0.Element.GetAttributeValueText("Text");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.tabPageList, false, new RecordItemIndex(16));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
