///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LinkVendorErp recording.
    /// </summary>
    [TestModule("4a60ef5e-3aac-4e2e-b125-7cf197d16906", ModuleType.Recording, 1)]
    public partial class LinkVendorErp : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static LinkVendorErp instance = new LinkVendorErp();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LinkVendorErp()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LinkVendorErp Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Refresh' at Center.", repo.MainWindow.NavigationPanel.RefreshInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.Refresh.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.VendorSearch' at Center.", repo.MainWindow.NavigationPanel.VendorSearchInfo, new RecordItemIndex(1));
            repo.MainWindow.NavigationPanel.VendorSearch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'RANOREX' with focus on 'MainWindow.NavigationPanel.VendorSearch'.", repo.MainWindow.NavigationPanel.VendorSearchInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.VendorSearch.PressKeys("RANOREX");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.RANOREXCREATED' at Center.", repo.MainWindow.NavigationPanel.RANOREXCREATEDInfo, new RecordItemIndex(3));
            repo.MainWindow.NavigationPanel.RANOREXCREATED.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.VendorNameTextBox' at Center.", repo.MainWindow.NavigationPanel.VendorNameTextBoxInfo, new RecordItemIndex(4));
            repo.MainWindow.NavigationPanel.VendorNameTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'ats' on item 'MainWindow.NavigationPanel.VendorNameTextBox'.", repo.MainWindow.NavigationPanel.VendorNameTextBoxInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.VendorNameTextBox.Element.SetAttributeValue("Text", "ats");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Search' at Center.", repo.MainWindow.NavigationPanel.SearchInfo, new RecordItemIndex(6));
            repo.MainWindow.NavigationPanel.Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'MainWindow.NavigationPanel.SomeCheckBox1'", repo.MainWindow.NavigationPanel.SomeCheckBox1Info, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.SomeCheckBox1Info.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SomeCheckBox1' at Center.", repo.MainWindow.NavigationPanel.SomeCheckBox1Info, new RecordItemIndex(8));
            repo.MainWindow.NavigationPanel.SomeCheckBox1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NotificationsWindow.SuccessfullyLinked'.", repo.NotificationsWindow.SuccessfullyLinkedInfo, new RecordItemIndex(9));
            Validate.Exists(repo.NotificationsWindow.SuccessfullyLinkedInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(11));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
