///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The LoginDevSPWeb recording.
    /// </summary>
    [TestModule("973f7bf5-fbed-4b2a-8654-c4497c331cc1", ModuleType.Recording, 1)]
    public partial class LoginDevSPWeb : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static LoginDevSPWeb instance = new LoginDevSPWeb();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public LoginDevSPWeb()
        {
            varEmail = "";
            varSPwebsite = "https://ca10a2061.atsna.atsauto.net/";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static LoginDevSPWeb Instance
        {
            get { return instance; }
        }

#region Variables

        string _varEmail;

        /// <summary>
        /// Gets or sets the value of variable varEmail.
        /// </summary>
        [TestVariable("bed0ce5d-b687-4609-8d8f-040601cd1afe")]
        public string varEmail
        {
            get { return _varEmail; }
            set { _varEmail = value; }
        }

        string _varSPwebsite;

        /// <summary>
        /// Gets or sets the value of variable varSPwebsite.
        /// </summary>
        [TestVariable("f4076e01-7bb0-41ef-88d1-91637ba6bb76")]
        public string varSPwebsite
        {
            get { return _varSPwebsite; }
            set { _varSPwebsite = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $varSPwebsite with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser(varSPwebsite, "Chrome", "", false, true, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Email' at Center.", repo.LoginATSSupplierPortal.EmailInfo, new RecordItemIndex(1));
            repo.LoginATSSupplierPortal.Email.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varEmail' with focus on 'LoginATSSupplierPortal.Email'.", repo.LoginATSSupplierPortal.EmailInfo, new RecordItemIndex(2));
            repo.LoginATSSupplierPortal.Email.PressKeys(varEmail);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Password' at Center.", repo.LoginATSSupplierPortal.PasswordInfo, new RecordItemIndex(3));
            repo.LoginATSSupplierPortal.Password.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'SupplierPortalRocks' with focus on 'LoginATSSupplierPortal.Password'.", repo.LoginATSSupplierPortal.PasswordInfo, new RecordItemIndex(4));
            repo.LoginATSSupplierPortal.Password.PressKeys("SupplierPortalRocks");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.SpanTagLogin' at Center.", repo.LoginATSSupplierPortal.SpanTagLoginInfo, new RecordItemIndex(5));
            repo.LoginATSSupplierPortal.SpanTagLogin.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
