///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ModifyPO recording.
    /// </summary>
    [TestModule("df3668de-887c-411a-b968-fb913c6bd403", ModuleType.Recording, 1)]
    public partial class ModifyPO : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ModifyPO instance = new ModifyPO();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ModifyPO()
        {
            varJDEOrderNumber = "";
            varRFQNumber = "11756";
            varNote = "Approve Me";
            varPath = "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RFQNumber\\RFQNumber.txt";
            varDate = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ModifyPO Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNote;

        /// <summary>
        /// Gets or sets the value of variable varNote.
        /// </summary>
        [TestVariable("dfda569a-9bf3-4045-bd89-ad584cd6343e")]
        public string varNote
        {
            get { return _varNote; }
            set { _varNote = value; }
        }

        string _varPath;

        /// <summary>
        /// Gets or sets the value of variable varPath.
        /// </summary>
        [TestVariable("5e2d67d8-c2bb-45f1-b6ba-ca0fa3b87ec0")]
        public string varPath
        {
            get { return _varPath; }
            set { _varPath = value; }
        }

        string _varDate;

        /// <summary>
        /// Gets or sets the value of variable varDate.
        /// </summary>
        [TestVariable("5e873ecc-3752-47d9-8328-8d807a1a496f")]
        public string varDate
        {
            get { return _varDate; }
            set { _varDate = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varJDEOrderNumber.
        /// </summary>
        [TestVariable("76dddbdf-9b0d-45b5-a9e4-914582f0d2e6")]
        public string varJDEOrderNumber
        {
            get { return repo.varJDEOrderNumber; }
            set { repo.varJDEOrderNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("b7249ef5-2e88-40c8-848c-19728b90d7f7")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varRFQNumber = SPCollection.ReadRequisitionFile(varPath);
            Delay.Milliseconds(0);
            
            varJDEOrderNumber = SPCollection.SQLQueryJDEReturnOrderNumber(varRFQNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'LoginATSSupplierPortal.Search1'", repo.LoginATSSupplierPortal.Search1Info, new ActionTimeout(300000), new RecordItemIndex(2));
            repo.LoginATSSupplierPortal.Search1Info.WaitForExists(300000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to not exist. Associated repository item: 'RFQListingATSSupplierPortal.Loading'", repo.RFQListingATSSupplierPortal.LoadingInfo, new ActionTimeout(180000), new RecordItemIndex(3));
            repo.RFQListingATSSupplierPortal.LoadingInfo.WaitForNotExists(180000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Search1' at Center.", repo.LoginATSSupplierPortal.Search1Info, new RecordItemIndex(5));
            repo.LoginATSSupplierPortal.Search1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varJDEOrderNumber' with focus on 'LoginATSSupplierPortal.Search1'.", repo.LoginATSSupplierPortal.Search1Info, new RecordItemIndex(6));
            repo.LoginATSSupplierPortal.Search1.PressKeys(varJDEOrderNumber, 1000);
            Delay.Milliseconds(2000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(7));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varJDEOrderNumber) on item 'LoginATSSupplierPortal.OrderNumberRow0'.", repo.LoginATSSupplierPortal.OrderNumberRow0Info, new RecordItemIndex(8));
            Validate.AttributeEqual(repo.LoginATSSupplierPortal.OrderNumberRow0Info, "InnerText", varJDEOrderNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(9));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.OrderNumberRow0' at Center.", repo.LoginATSSupplierPortal.OrderNumberRow0Info, new RecordItemIndex(10));
            repo.LoginATSSupplierPortal.OrderNumberRow0.Click();
            Delay.Milliseconds(200);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'LoginATSSupplierPortal.OrderNumberRow0' at Center.", repo.LoginATSSupplierPortal.OrderNumberRow0Info, new RecordItemIndex(11));
                repo.LoginATSSupplierPortal.OrderNumberRow0.Click();
                Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(11)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'LoginATSSupplierPortal.NotesRow0'", repo.LoginATSSupplierPortal.NotesRow0Info, new ActionTimeout(10000), new RecordItemIndex(12));
            repo.LoginATSSupplierPortal.NotesRow0Info.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.TableRow1' at Center.", repo.LoginATSSupplierPortal.TableRow1Info, new RecordItemIndex(13));
            repo.LoginATSSupplierPortal.TableRow1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.TableRow2' at Center.", repo.LoginATSSupplierPortal.TableRow2Info, new RecordItemIndex(14));
            repo.LoginATSSupplierPortal.TableRow2.Click();
            Delay.Milliseconds(200);
            
            varDate = SPCollection.GetDateTimePlusXDays(ValueConverter.ArgumentFromString<int>("days", "365"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varDate, new RecordItemIndex(16));
            
            //varDate = SPCollection.ConvertDateYYYY(varDate);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", varDate, new RecordItemIndex(18));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BulkDate' at Center.", repo.LoginATSSupplierPortal.BulkDateInfo, new RecordItemIndex(19));
            repo.LoginATSSupplierPortal.BulkDate.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'LoginATSSupplierPortal.BulkDate'.", repo.LoginATSSupplierPortal.BulkDateInfo, new RecordItemIndex(20));
            //repo.LoginATSSupplierPortal.BulkDate.Element.SetAttributeValue("InnerText", "");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}' with focus on 'LoginATSSupplierPortal.BulkDate'.", repo.LoginATSSupplierPortal.BulkDateInfo, new RecordItemIndex(21));
            repo.LoginATSSupplierPortal.BulkDate.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varDate' with focus on 'LoginATSSupplierPortal.BulkDate'.", repo.LoginATSSupplierPortal.BulkDateInfo, new RecordItemIndex(22));
            repo.LoginATSSupplierPortal.BulkDate.PressKeys(varDate);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varDate' on item 'LoginATSSupplierPortal.BulkDate'.", repo.LoginATSSupplierPortal.BulkDateInfo, new RecordItemIndex(23));
            //repo.LoginATSSupplierPortal.BulkDate.Element.SetAttributeValue("InnerText", varDate);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.ApplySelectedDate' at Center.", repo.LoginATSSupplierPortal.ApplySelectedDateInfo, new RecordItemIndex(24));
            repo.LoginATSSupplierPortal.ApplySelectedDate.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(25));
            Delay.Duration(3000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.NotesRow0' at Center.", repo.LoginATSSupplierPortal.NotesRow0Info, new RecordItemIndex(26));
            repo.LoginATSSupplierPortal.NotesRow0.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varNote' with focus on 'LoginATSSupplierPortal.NotesRow0'.", repo.LoginATSSupplierPortal.NotesRow0Info, new RecordItemIndex(27));
            repo.LoginATSSupplierPortal.NotesRow0.PressKeys(varNote);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.OpenPOsTableInfo' at Center.", repo.LoginATSSupplierPortal.OpenPOsTableInfoInfo, new RecordItemIndex(28));
            repo.LoginATSSupplierPortal.OpenPOsTableInfo.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Right}{Right}'.", new RecordItemIndex(29));
            Keyboard.Press("{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(30));
            //repo.LoginATSSupplierPortal.BtnSubmit.Click();
            //Delay.Milliseconds(200);
            
            ClickButtonSubmit();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(32));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.LoginATSSupplierPortal.Self, false, new RecordItemIndex(33));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
