///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SearchJDEforCancelledLines recording.
    /// </summary>
    [TestModule("8cb85673-d2da-4cea-91f1-988504eb2b9d", ModuleType.Recording, 1)]
    public partial class SearchJDEforCancelledLines : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SearchJDEforCancelledLines instance = new SearchJDEforCancelledLines();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SearchJDEforCancelledLines()
        {
            varUserReferences = "";
            varQty = "1";
            varColumnIndex = "";
            varLinkCellText = "";
            varJDEOrderNo = "";
            varJDELineNo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SearchJDEforCancelledLines Instance
        {
            get { return instance; }
        }

#region Variables

        string _varUserReferences;

        /// <summary>
        /// Gets or sets the value of variable varUserReferences.
        /// </summary>
        [TestVariable("318dca26-5880-40cf-a2e6-75d3272bd5d5")]
        public string varUserReferences
        {
            get { return _varUserReferences; }
            set { _varUserReferences = value; }
        }

        string _varQty;

        /// <summary>
        /// Gets or sets the value of variable varQty.
        /// </summary>
        [TestVariable("7c8b4af6-e714-4ac1-8882-99068e886f0c")]
        public string varQty
        {
            get { return _varQty; }
            set { _varQty = value; }
        }

        string _varLinkCellText;

        /// <summary>
        /// Gets or sets the value of variable varLinkCellText.
        /// </summary>
        [TestVariable("6fd645ef-face-49ef-a26e-c5aeb6fb637e")]
        public string varLinkCellText
        {
            get { return _varLinkCellText; }
            set { _varLinkCellText = value; }
        }

        string _varJDELineNo;

        /// <summary>
        /// Gets or sets the value of variable varJDELineNo.
        /// </summary>
        [TestVariable("c849b51b-bc00-413f-9547-614b732a024c")]
        public string varJDELineNo
        {
            get { return _varJDELineNo; }
            set { _varJDELineNo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varColumnIndex.
        /// </summary>
        [TestVariable("4bd3d8ca-29dd-4cae-a495-50d20ffed5d5")]
        public string varColumnIndex
        {
            get { return repo.varcolumnIndex; }
            set { repo.varcolumnIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varJDEOrderNo.
        /// </summary>
        [TestVariable("61f72162-647e-408e-9b97-2a709834ee7b")]
        public string varJDEOrderNo
        {
            get { return repo.varJDEOrderNo; }
            set { repo.varJDEOrderNo = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.PurchasingGeneral' at Center.", repo.JDEPath.PurchasingGeneralInfo, new RecordItemIndex(0));
            repo.JDEPath.PurchasingGeneral.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.ViewAllDocTypes' at Center.", repo.JDEPath.ViewAllDocTypesInfo, new RecordItemIndex(1));
            repo.JDEPath.ViewAllDocTypes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'JDEPath.UserReferenceTextBox'.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(2));
            repo.JDEPath.UserReferenceTextBox.Element.SetAttributeValue("InnerText", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.UserReferenceTextBox' at Center.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(3));
            repo.JDEPath.UserReferenceTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUserReferences' with focus on 'JDEPath.UserReferenceTextBox'.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(4));
            repo.JDEPath.UserReferenceTextBox.PressKeys(varUserReferences);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.SupplierSO' at Center.", repo.JDEPath.SupplierSOInfo, new RecordItemIndex(5));
            repo.JDEPath.SupplierSO.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'JDEPath.SupplierSO' at Center.", repo.JDEPath.SupplierSOInfo, new RecordItemIndex(6));
            //repo.JDEPath.SupplierSO.Click(System.Windows.Forms.MouseButtons.Right);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Chrome.Paste' at Center.", repo.Chrome.PasteInfo, new RecordItemIndex(7));
            //repo.Chrome.Paste.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(8));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Vkey}{LControlKey up}'.", new RecordItemIndex(9));
            Keyboard.Press("{LControlKey down}{Vkey}{LControlKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.QtyToRecv' at Center.", repo.JDEPath.QtyToRecvInfo, new RecordItemIndex(10));
            repo.JDEPath.QtyToRecv.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varQty' on item 'JDEPath.QtyToRecv'.", repo.JDEPath.QtyToRecvInfo, new RecordItemIndex(11));
            //repo.JDEPath.QtyToRecv.Element.SetAttributeValue("InnerText", varQty);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(12));
            repo.JDEPath.Find.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(13));
            repo.JDEPath.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to not exist. Associated repository item: 'JDEPath.AfProgressIndicatorIndeterminate'", repo.JDEPath.AfProgressIndicatorIndeterminateInfo, new ActionTimeout(60000), new RecordItemIndex(14));
            repo.JDEPath.AfProgressIndicatorIndeterminateInfo.WaitForNotExists(60000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='125') on item 'JDEPath.JdeGridData010.LastStatusRow0'.", repo.JDEPath.JdeGridData010.LastStatusRow0Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.LastStatusRow0Info, "InnerText", "125");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='981') on item 'JDEPath.JdeGridData010.NextStatusRow0'.", repo.JDEPath.JdeGridData010.NextStatusRow0Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.NextStatusRow0Info, "InnerText", "981");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Activate() on item 'MainWindow'.", repo.MainWindow.SelfInfo, new RecordItemIndex(18));
            repo.MainWindow.Self.Activate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'True' on item 'MainWindow.NavigationPanel.CheckBoxItem1'.", repo.MainWindow.NavigationPanel.CheckBoxItem1Info, new RecordItemIndex(19));
            repo.MainWindow.NavigationPanel.CheckBoxItem1.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Row0Cell3' at Center.", repo.MainWindow.NavigationPanel.Row0Cell3Info, new RecordItemIndex(20));
            repo.MainWindow.NavigationPanel.Row0Cell3.Click();
            Delay.Milliseconds(200);
            
            //varColumnIndex = ValueConverter.ToString(SPCollection.GetColumnIndexofHeader("Link"));
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Text' from item 'MainWindow.NavigationPanel.FileNameofFirstDocumentLink' and assigning its value to variable 'varLinkCellText'.", repo.MainWindow.NavigationPanel.FileNameofFirstDocumentLinkInfo, new RecordItemIndex(22));
            //varLinkCellText = repo.MainWindow.NavigationPanel.FileNameofFirstDocumentLink.Element.GetAttributeValueText("Text");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", varLinkCellText, new RecordItemIndex(23));
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.tabPageList, false, new RecordItemIndex(24));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s for the attribute 'Enabled' to equal the specified value 'True'. Associated repository item: 'MainWindow.UnprocessedCancelDetailsButton'", repo.MainWindow.UnprocessedCancelDetailsButtonInfo, new RecordItemIndex(25));
            repo.MainWindow.UnprocessedCancelDetailsButtonInfo.WaitForAttributeEqual(30000, "Enabled", "True");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainWindow.UnprocessedCancelDetailsButton' at Center.", repo.MainWindow.UnprocessedCancelDetailsButtonInfo, new RecordItemIndex(26));
            repo.MainWindow.UnprocessedCancelDetailsButton.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.UnprocessedCancelDetailsButton' at Center.", repo.MainWindow.UnprocessedCancelDetailsButtonInfo, new RecordItemIndex(27));
            repo.MainWindow.UnprocessedCancelDetailsButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmDelete.ButtonYes' at Center.", repo.ConfirmDelete.ButtonYesInfo, new RecordItemIndex(28));
            repo.ConfirmDelete.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'NotificationsWindow.CloseButton'", repo.NotificationsWindow.CloseButtonInfo, new ActionTimeout(30000), new RecordItemIndex(29));
            repo.NotificationsWindow.CloseButtonInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.NotificationsWindow.Self, false, new RecordItemIndex(30));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotificationsWindow.CloseButton' at Center.", repo.NotificationsWindow.CloseButtonInfo, new RecordItemIndex(31));
            repo.NotificationsWindow.CloseButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(32));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Activate() on item 'WorkWithOrderDetailsInternetExplo'.", repo.WorkWithOrderDetailsInternetExplo.SelfInfo, new RecordItemIndex(33));
            repo.WorkWithOrderDetailsInternetExplo.Self.Activate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(34));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(35));
            repo.JDEPath.Find.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(36));
            repo.JDEPath.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to not exist. Associated repository item: 'JDEPath.AfProgressIndicatorIndeterminate'", repo.JDEPath.AfProgressIndicatorIndeterminateInfo, new ActionTimeout(60000), new RecordItemIndex(37));
            repo.JDEPath.AfProgressIndicatorIndeterminateInfo.WaitForNotExists(60000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='980') on item 'JDEPath.JdeGridData010.LastStatusRow0'.", repo.JDEPath.JdeGridData010.LastStatusRow0Info, new RecordItemIndex(38));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.LastStatusRow0Info, "InnerText", "980");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='999') on item 'JDEPath.JdeGridData010.NextStatusRow0'.", repo.JDEPath.JdeGridData010.NextStatusRow0Info, new RecordItemIndex(39));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.NextStatusRow0Info, "InnerText", "999");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='192257') on item 'JDEPath.JdeGridData010.BuyerNumberRow0'.", repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, new RecordItemIndex(40));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, "InnerText", "192257");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.JdeGridData010.OrderNumber' and assigning its value to variable 'varJDEOrderNo'.", repo.JDEPath.JdeGridData010.OrderNumberInfo, new RecordItemIndex(41));
            varJDEOrderNo = repo.JDEPath.JdeGridData010.OrderNumber.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.JdeGridData010.LineNumber' and assigning its value to variable 'varJDELineNo'.", repo.JDEPath.JdeGridData010.LineNumberInfo, new RecordItemIndex(42));
            varJDELineNo = repo.JDEPath.JdeGridData010.LineNumber.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            ValidateLedgerTableEntries(varJDEOrderNo, varJDELineNo, "BSSV-SP", "192257");
            Delay.Milliseconds(0);
            
            //ValidateLedgerTableEntries("429113", "1.000", "BSSV-SP", "192257");
            //Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(45));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
