///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace ATS_Supplier_Portal_Test
{
    public partial class SelectWinner
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ClickCellName(string rowName, string colName)
        {
            var tableRxpath = "/form[@title='MainWindow']/list[@automationid='navigationPanel']/tabpagelist//table";
            var cellText = SPCollection.ReturnCellValue(tableRxpath, SPCollection.GetColumnIndexofTable(tableRxpath, rowName, true), 
                                                         SPCollection.GetColumnIndexofTable(tableRxpath, colName, false), false, true);
        }

    }
}
