///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SortDetailsRFQ recording.
    /// </summary>
    [TestModule("97ed3f6c-057b-46c0-93b6-a21f3edc1cd8", ModuleType.Recording, 1)]
    public partial class SortDetailsRFQ : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SortDetailsRFQ instance = new SortDetailsRFQ();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SortDetailsRFQ()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SortDetailsRFQ Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Details' at Center.", repo.MainWindow.NavigationPanel.DetailsInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.Details.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'MainWindow.BusyOverlayLoaded'", repo.MainWindow.BusyOverlayLoadedInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.MainWindow.BusyOverlayLoadedInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Detail1' at Center.", repo.MainWindow.NavigationPanel.Detail1Info, new RecordItemIndex(4));
            repo.MainWindow.NavigationPanel.Detail1.Click();
            Delay.Milliseconds(200);
            
            SPCollection.SortDetailColumns("Detail");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Revision1' at Center.", repo.MainWindow.NavigationPanel.Revision1Info, new RecordItemIndex(6));
            repo.MainWindow.NavigationPanel.Revision1.Click();
            Delay.Milliseconds(200);
            
            SPCollection.SortDetailColumns("Revision");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Description1' at Center.", repo.MainWindow.NavigationPanel.Description1Info, new RecordItemIndex(8));
            repo.MainWindow.NavigationPanel.Description1.Click();
            Delay.Milliseconds(200);
            
            SPCollection.SortDetailColumns("Description");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextQty1' at Center.", repo.MainWindow.NavigationPanel.TextQty1Info, new RecordItemIndex(10));
            repo.MainWindow.NavigationPanel.TextQty1.Click();
            Delay.Milliseconds(200);
            
            SPCollection.SortDetailColumns("Qty");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton1' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButton1Info, new RecordItemIndex(12));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton1.MoveTo();
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(1700);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton1' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButton1Info, new RecordItemIndex(13));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton1.MoveTo();
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(14));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainWindow.NavigationPanel.Kitting1' at Center.", repo.MainWindow.NavigationPanel.Kitting1Info, new RecordItemIndex(15));
            //repo.MainWindow.NavigationPanel.Kitting1.MoveTo();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Kitting1' at Center.", repo.MainWindow.NavigationPanel.Kitting1Info, new RecordItemIndex(16));
            //repo.MainWindow.NavigationPanel.Kitting1.Click();
            //Delay.Milliseconds(200);
            
            //SPCollection.SortDetailColumns("Kitting");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
