///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SortDetails recording.
    /// </summary>
    [TestModule("269bd206-9008-4a6d-8a71-26b8af35ff2f", ModuleType.Recording, 1)]
    public partial class SortDetails : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SortDetails instance = new SortDetails();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SortDetails()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SortDetails Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQ' at Center.", repo.MainWindow.NavigationPanel.CreateRFQInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.CreateRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(60000), new RecordItemIndex(1));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailsInBatch' at Center.", repo.MainWindow.NavigationPanel.DetailsInBatchInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.DetailsInBatch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '90000' on item 'MainWindow.NavigationPanel.UserReferenceFilter'.", repo.MainWindow.NavigationPanel.UserReferenceFilterInfo, new RecordItemIndex(3));
            repo.MainWindow.NavigationPanel.UserReferenceFilter.Element.SetAttributeValue("Text", "90000");
            Delay.Milliseconds(0);
            
            SPCollection.ValidateSorting("Detail");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Revision' at Center.", repo.MainWindow.NavigationPanel.RevisionInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.Revision.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("Revision");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Description' at Center.", repo.MainWindow.NavigationPanel.DescriptionInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.Description.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("Description");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.TextQty' at Center.", repo.MainWindow.NavigationPanel.TextQtyInfo, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.TextQty.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("Qty");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.tabPageList, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(12));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(13));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ProjectNo' at Center.", repo.MainWindow.NavigationPanel.ProjectNoInfo, new RecordItemIndex(14));
            repo.MainWindow.NavigationPanel.ProjectNo.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("ProjectNo");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(16));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(700);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(17));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Designer' at Center.", repo.MainWindow.NavigationPanel.DesignerInfo, new RecordItemIndex(18));
            repo.MainWindow.NavigationPanel.Designer.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("Designer");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(20));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(21));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Kitting' at Center.", repo.MainWindow.NavigationPanel.KittingInfo, new RecordItemIndex(22));
            repo.MainWindow.NavigationPanel.Kitting.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("Kitting");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(24));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(25));
            repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.UserReference' at Center.", repo.MainWindow.NavigationPanel.UserReferenceInfo, new RecordItemIndex(26));
            repo.MainWindow.NavigationPanel.UserReference.Click();
            Delay.Milliseconds(200);
            
            SPCollection.ValidateSorting("User Reference");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Line' at Center.", repo.MainWindow.NavigationPanel.LineInfo, new RecordItemIndex(28));
            //repo.MainWindow.NavigationPanel.Line.Click();
            //Delay.Milliseconds(200);
            
            //SPCollection.ValidateSorting("Line");
            //Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.tabPageList, false, new RecordItemIndex(30));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
