///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateOrderNumberJDE recording.
    /// </summary>
    [TestModule("56828220-67cd-4b82-98cb-e3a539704d66", ModuleType.Recording, 1)]
    public partial class ValidateOrderNumberJDE : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ValidateOrderNumberJDE instance = new ValidateOrderNumberJDE();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateOrderNumberJDE()
        {
            varJDEOrderNumber = "";
            varDate = "";
            varRFQNumber = "11756";
            varATSReqDate = "";
            varNumRecords = "";
            varNumEntries = "";
            varShippingMethod = "yourValue";
            varRequestedShipDate = "yourValue";
            varOriginalOrderNo = "";
            varOriginalLineNo = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateOrderNumberJDE Instance
        {
            get { return instance; }
        }

#region Variables

        string _varDate;

        /// <summary>
        /// Gets or sets the value of variable varDate.
        /// </summary>
        [TestVariable("8f0340f5-18c0-4073-8305-b339dcdbab3f")]
        public string varDate
        {
            get { return _varDate; }
            set { _varDate = value; }
        }

        string _varATSReqDate;

        /// <summary>
        /// Gets or sets the value of variable varATSReqDate.
        /// </summary>
        [TestVariable("2aa9fe78-aeae-425e-9069-f886cffa2080")]
        public string varATSReqDate
        {
            get { return _varATSReqDate; }
            set { _varATSReqDate = value; }
        }

        string _varNumRecords;

        /// <summary>
        /// Gets or sets the value of variable varNumRecords.
        /// </summary>
        [TestVariable("5152da6e-4a35-4edc-9ad5-e715c43ce2bb")]
        public string varNumRecords
        {
            get { return _varNumRecords; }
            set { _varNumRecords = value; }
        }

        string _varNumEntries;

        /// <summary>
        /// Gets or sets the value of variable varNumEntries.
        /// </summary>
        [TestVariable("bad41ec5-41a4-4bb4-a8cd-749b7bfd048b")]
        public string varNumEntries
        {
            get { return _varNumEntries; }
            set { _varNumEntries = value; }
        }

        string _varShippingMethod;

        /// <summary>
        /// Gets or sets the value of variable varShippingMethod.
        /// </summary>
        [TestVariable("9e1ce741-92ca-4140-a1c6-fb28509af53a")]
        public string varShippingMethod
        {
            get { return _varShippingMethod; }
            set { _varShippingMethod = value; }
        }

        string _varRequestedShipDate;

        /// <summary>
        /// Gets or sets the value of variable varRequestedShipDate.
        /// </summary>
        [TestVariable("b101f4ed-5fd2-46f6-ae45-713f7fd8a0dd")]
        public string varRequestedShipDate
        {
            get { return _varRequestedShipDate; }
            set { _varRequestedShipDate = value; }
        }

        string _varOriginalOrderNo;

        /// <summary>
        /// Gets or sets the value of variable varOriginalOrderNo.
        /// </summary>
        [TestVariable("411ce839-717d-4d98-a3f6-c7e1b4f6fd42")]
        public string varOriginalOrderNo
        {
            get { return _varOriginalOrderNo; }
            set { _varOriginalOrderNo = value; }
        }

        string _varOriginalLineNo;

        /// <summary>
        /// Gets or sets the value of variable varOriginalLineNo.
        /// </summary>
        [TestVariable("f93778d6-39a9-4cf3-94df-17d73f243132")]
        public string varOriginalLineNo
        {
            get { return _varOriginalLineNo; }
            set { _varOriginalLineNo = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varJDEOrderNumber.
        /// </summary>
        [TestVariable("d7ed5569-ba1a-46d7-acc9-e659ce96e38c")]
        public string varJDEOrderNumber
        {
            get { return repo.varJDEOrderNumber; }
            set { repo.varJDEOrderNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("39b7fa48-2bc1-4c85-a9bc-730dcdb63bc7")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varJDEOrderNumber = SPCollection.SQLQueryJDEReturnOrderNumber(varRFQNumber);
            Delay.Milliseconds(0);
            
            varATSReqDate = SPCollection.ConvertDate(varATSReqDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varATSReqDate, new RecordItemIndex(2));
            
            //varJDEOrderNumber = SPCollection.SQLQueryJDEReturnOrderNumber("927185");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", varJDEOrderNumber, new RecordItemIndex(4));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.PurchasingGeneral' at Center.", repo.JDEPath.PurchasingGeneralInfo, new RecordItemIndex(5));
            repo.JDEPath.PurchasingGeneral.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.ViewAllDocTypes' at Center.", repo.JDEPath.ViewAllDocTypesInfo, new RecordItemIndex(6));
            repo.JDEPath.ViewAllDocTypes.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(7));
            //repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", "");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(8));
            repo.JDEPath.InputTag013.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(9));
            repo.JDEPath.InputTag013.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}' with focus on 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(10));
            repo.JDEPath.InputTag013.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varJDEOrderNumber' with focus on 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(11));
            repo.JDEPath.InputTag013.PressKeys(varJDEOrderNumber);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varJDEOrderNumber' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(12));
            //repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", varJDEOrderNumber);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(13));
            repo.JDEPath.Find.Click();
            Delay.Milliseconds(200);
            
            // Validating Last Status
            Report.Log(ReportLevel.Info, "Validation", "Validating Last Status\r\nValidating AttributeEqual (InnerText='230') on item 'JDEPath.JdeGridData010.LastStatusRow0'.", repo.JDEPath.JdeGridData010.LastStatusRow0Info, new RecordItemIndex(14));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.LastStatusRow0Info, "InnerText", "230");
            Delay.Milliseconds(0);
            
            // Validating Next Status
            Report.Log(ReportLevel.Info, "Validation", "Validating Next Status\r\nValidating AttributeEqual (InnerText='280') on item 'JDEPath.JdeGridData010.NextStatusRow0'.", repo.JDEPath.JdeGridData010.NextStatusRow0Info, new RecordItemIndex(15));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.NextStatusRow0Info, "InnerText", "280");
            Delay.Milliseconds(0);
            
            // Validating Supplier Number for ANCHOR DANLY
            Report.Log(ReportLevel.Info, "Validation", "Validating Supplier Number for ANCHOR DANLY\r\nValidating AttributeEqual (InnerText='184173') on item 'JDEPath.JdeGridData010.SupplierNumberRow0'.", repo.JDEPath.JdeGridData010.SupplierNumberRow0Info, new RecordItemIndex(16));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.SupplierNumberRow0Info, "InnerText", "184173");
            Delay.Milliseconds(0);
            
            // Validating ATS Promise Date
            //Report.Log(ReportLevel.Info, "Validation", "Validating ATS Promise Date\r\nValidating AttributeEqual (InnerText=$varDate) on item 'JDEPath.JdeGridData010.ATSPromDate'.", repo.JDEPath.JdeGridData010.ATSPromDateInfo, new RecordItemIndex(17));
            //Validate.AttributeEqual(repo.JDEPath.JdeGridData010.ATSPromDateInfo, "InnerText", varDate);
            //Delay.Milliseconds(0);
            
            // Validating ATS Request Date
            //Report.Log(ReportLevel.Info, "Validation", "Validating ATS Request Date\r\nValidating AttributeEqual (InnerText=$varATSReqDate) on item 'JDEPath.JdeGridData010.ATSRequestDate'.", repo.JDEPath.JdeGridData010.ATSRequestDateInfo, new RecordItemIndex(18));
            //Validate.AttributeEqual(repo.JDEPath.JdeGridData010.ATSRequestDateInfo, "InnerText", varATSReqDate);
            //Delay.Milliseconds(0);
            
            // Validating Promise Delivery Date
            //Report.Log(ReportLevel.Info, "Validation", "Validating Promise Delivery Date\r\nValidating AttributeEqual (InnerText=$varDate) on item 'JDEPath.JdeGridData010.PromiseDeliveryDate'.", repo.JDEPath.JdeGridData010.PromiseDeliveryDateInfo, new RecordItemIndex(19));
            //Validate.AttributeEqual(repo.JDEPath.JdeGridData010.PromiseDeliveryDateInfo, "InnerText", varDate);
            //Delay.Milliseconds(0);
            
            // Validating Buyer Number for User RanorexRT
            Report.Log(ReportLevel.Info, "Validation", "Validating Buyer Number for User RanorexRT\r\nValidating AttributeEqual (InnerText='192257') on item 'JDEPath.JdeGridData010.BuyerNumberRow0'.", repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, new RecordItemIndex(20));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, "InnerText", "192257");
            Delay.Milliseconds(0);
            
            ShortenShippingMethod();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varShippingMethod) on item 'JDEPath.JdeGridData010.ShippingMethod'.", repo.JDEPath.JdeGridData010.ShippingMethodInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.ShippingMethodInfo, "InnerText", varShippingMethod);
            Delay.Milliseconds(0);
            
            varRequestedShipDate = SPCollection.ConvertDate(varRequestedShipDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varRequestedShipDate, new RecordItemIndex(24));
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varRequestedShipDate) on item 'JDEPath.JdeGridData010.RequestedShipDate'.", repo.JDEPath.JdeGridData010.RequestedShipDateInfo, new RecordItemIndex(25));
            //Validate.AttributeEqual(repo.JDEPath.JdeGridData010.RequestedShipDateInfo, "InnerText", varRequestedShipDate);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varRequestedShipDate) on item 'JDEPath.JdeGridData010.RequestedShipDate'.", repo.JDEPath.JdeGridData010.RequestedShipDateInfo, new RecordItemIndex(26));
            //Validate.AttributeEqual(repo.JDEPath.JdeGridData010.RequestedShipDateInfo, "InnerText", varRequestedShipDate);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.JdeGridData010.OriginalOrderNo' and assigning its value to variable 'varOriginalOrderNo'.", repo.JDEPath.JdeGridData010.OriginalOrderNoInfo, new RecordItemIndex(27));
            varOriginalOrderNo = repo.JDEPath.JdeGridData010.OriginalOrderNo.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.JdeGridData010.OriginalLineNo' and assigning its value to variable 'varOriginalLineNo'.", repo.JDEPath.JdeGridData010.OriginalLineNoInfo, new RecordItemIndex(28));
            varOriginalLineNo = repo.JDEPath.JdeGridData010.OriginalLineNo.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.NumRecords' and assigning the part of its value captured by '\\d+(?!.*\\d+)' to variable 'varNumRecords'.", repo.JDEPath.NumRecordsInfo, new RecordItemIndex(29));
            varNumRecords = repo.JDEPath.NumRecords.Element.GetAttributeValueText("InnerText", new Regex("\\d+(?!.*\\d+)"));
            Delay.Milliseconds(0);
            
            ValidateOXClosedinJDELedgerTable(varOriginalOrderNo, varOriginalLineNo, "BSSV-SP", "192257");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(31));
            
            ValidateNumRecords();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(33));
            Delay.Duration(2000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
