///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateDeletedDetail recording.
    /// </summary>
    [TestModule("9a48a353-300e-422b-8d44-685f63608f3f", ModuleType.Recording, 1)]
    public partial class ValidateDeletedDetail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ValidateDeletedDetail instance = new ValidateDeletedDetail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateDeletedDetail()
        {
            varDetailNo = "";
            varReqNo = "";
            varLineNumber = "";
            varUserReferenceNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateDeletedDetail Instance
        {
            get { return instance; }
        }

#region Variables

        string _varDetailNo;

        /// <summary>
        /// Gets or sets the value of variable varDetailNo.
        /// </summary>
        [TestVariable("236cbf85-ed2e-42d6-bc5a-f57726b12049")]
        public string varDetailNo
        {
            get { return _varDetailNo; }
            set { _varDetailNo = value; }
        }

        string _varReqNo;

        /// <summary>
        /// Gets or sets the value of variable varReqNo.
        /// </summary>
        [TestVariable("3aebb089-d3d8-4057-bebe-d8ee4d07ed6c")]
        public string varReqNo
        {
            get { return _varReqNo; }
            set { _varReqNo = value; }
        }

        string _varLineNumber;

        /// <summary>
        /// Gets or sets the value of variable varLineNumber.
        /// </summary>
        [TestVariable("2865dbf2-b59e-4a51-bef2-47840e627d1c")]
        public string varLineNumber
        {
            get { return _varLineNumber; }
            set { _varLineNumber = value; }
        }

        string _varUserReferenceNumber;

        /// <summary>
        /// Gets or sets the value of variable varUserReferenceNumber.
        /// </summary>
        [TestVariable("e265c492-28d4-471d-8ae4-61c1ae1a441b")]
        public string varUserReferenceNumber
        {
            get { return _varUserReferenceNumber; }
            set { _varUserReferenceNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varDetailNo = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RFQNumber\\DeletedDetailNumber.txt");
            Delay.Milliseconds(0);
            
            varReqNo = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RFQNumber\\DeletedRFQNumber.txt");
            Delay.Milliseconds(0);
            
            //varLineNumber = SPCollection.SQLQueryDetailNumber(varReqNo, varDetailNo);
            //Delay.Milliseconds(0);
            
            //varLineNumber = SPCollection.SQLQueryDetailNumber("9915403", "13605-0304-0002");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "User", varLineNumber, new RecordItemIndex(4));
            
            varUserReferenceNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RequisitionNumber\\req.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.CreateRFQ' at Center.", repo.MainWindow.NavigationPanel.CreateRFQInfo, new RecordItemIndex(6));
            repo.MainWindow.NavigationPanel.CreateRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailsInBatch' at Center.", repo.MainWindow.NavigationPanel.DetailsInBatchInfo, new RecordItemIndex(8));
            repo.MainWindow.NavigationPanel.DetailsInBatch.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(9));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varUserReferenceNumber' on item 'MainWindow.NavigationPanel.UserReferenceFilter'.", repo.MainWindow.NavigationPanel.UserReferenceFilterInfo, new RecordItemIndex(10));
            repo.MainWindow.NavigationPanel.UserReferenceFilter.Element.SetAttributeValue("Text", varUserReferenceNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(11));
            Delay.Duration(5000, false);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varLineNumber' on item 'MainWindow.NavigationPanel.LineFilter'.", repo.MainWindow.NavigationPanel.LineFilterInfo, new RecordItemIndex(12));
            //repo.MainWindow.NavigationPanel.LineFilter.Element.SetAttributeValue("Text", varLineNumber);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(13));
            //Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$varDetailNo' on item 'MainWindow.NavigationPanel.DetailsFilter'.", repo.MainWindow.NavigationPanel.DetailsFilterInfo, new RecordItemIndex(14));
            repo.MainWindow.NavigationPanel.DetailsFilter.Element.SetAttributeValue("Text", varDetailNo);
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(15));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(4700);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButtonInfo, new RecordItemIndex(16));
            //repo.MainWindow.NavigationPanel.PARTLineRightButton.MoveTo();
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(17));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text=$varDetailNo) on item 'MainWindow.NavigationPanel.DetailRow0'.", repo.MainWindow.NavigationPanel.DetailRow0Info, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.DetailRow0Info, "Text", varDetailNo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.UnprocessedDetailsGrid, false, new RecordItemIndex(19));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
