///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateQuoteSubmitted recording.
    /// </summary>
    [TestModule("ddca797f-b46e-43b3-87fd-3f4511943537", ModuleType.Recording, 1)]
    public partial class ValidateQuoteSubmitted : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ValidateQuoteSubmitted instance = new ValidateQuoteSubmitted();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateQuoteSubmitted()
        {
            varColIndex = "";
            varRowIndex = "";
            varResult = "";
            varRFQNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateQuoteSubmitted Instance
        {
            get { return instance; }
        }

#region Variables

        string _varColIndex;

        /// <summary>
        /// Gets or sets the value of variable varColIndex.
        /// </summary>
        [TestVariable("02c74046-4391-4f29-b815-b59072a86448")]
        public string varColIndex
        {
            get { return _varColIndex; }
            set { _varColIndex = value; }
        }

        string _varResult;

        /// <summary>
        /// Gets or sets the value of variable varResult.
        /// </summary>
        [TestVariable("09c77bd7-fd9e-41ce-8aa0-ffbc16899e3d")]
        public string varResult
        {
            get { return _varResult; }
            set { _varResult = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRowIndex.
        /// </summary>
        [TestVariable("31db3ef6-f807-4b7a-b06e-cbd8aae4e3f8")]
        public string varRowIndex
        {
            get { return repo.varRowIndex; }
            set { repo.varRowIndex = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("7a2435d1-715d-4616-bf1f-98e961e0c32c")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Vendors' at Center.", repo.MainWindow.NavigationPanel.VendorsInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.Vendors.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(1));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'MainWindow.NavigationPanel.ATSDreaminPng'.", repo.MainWindow.NavigationPanel.ATSDreaminPngInfo, new RecordItemIndex(2));
            Validate.Exists(repo.MainWindow.NavigationPanel.ATSDreaminPngInfo);
            Delay.Milliseconds(0);
            
            ValidateCheckBox();
            Delay.Milliseconds(0);
            
            ValidateQuoteNumber();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Random Note here') on item 'MainWindow.NavigationPanel.RandomNoteHere'.", repo.MainWindow.NavigationPanel.RandomNoteHereInfo, new RecordItemIndex(5));
            Validate.AttributeEqual(repo.MainWindow.NavigationPanel.RandomNoteHereInfo, "Text", "Random Note here");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.NavigationPanel.SomeTabPageList, false, new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Details' at Center.", repo.MainWindow.NavigationPanel.DetailsInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.Details.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Detail1' at Center.", repo.MainWindow.NavigationPanel.Detail1Info, new RecordItemIndex(8));
            repo.MainWindow.NavigationPanel.Detail1.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'MainWindow.NavigationPanel.PARTLineRightButton1' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButton1Info, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.PARTLineRightButton1.MoveTo();
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(4700);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'MainWindow.NavigationPanel.PARTLineRightButton1' at Center.", repo.MainWindow.NavigationPanel.PARTLineRightButton1Info, new RecordItemIndex(10));
            repo.MainWindow.NavigationPanel.PARTLineRightButton1.MoveTo();
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            SPCollection.ValidatePricesinDetailsTab();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(12));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
