///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CheckSupplierPortalForReqNumber recording.
    /// </summary>
    [TestModule("69018ed1-3ff7-4048-b3ad-5d2befd2afaa", ModuleType.Recording, 1)]
    public partial class CheckSupplierPortalForReqNumber : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static CheckSupplierPortalForReqNumber instance = new CheckSupplierPortalForReqNumber();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CheckSupplierPortalForReqNumber()
        {
            varReqNumber = "";
            varServerName = "US18A2026";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CheckSupplierPortalForReqNumber Instance
        {
            get { return instance; }
        }

#region Variables

        string _varReqNumber;

        /// <summary>
        /// Gets or sets the value of variable varReqNumber.
        /// </summary>
        [TestVariable("2c8d0b85-6877-450c-99f5-e94d7eafbcf9")]
        public string varReqNumber
        {
            get { return _varReqNumber; }
            set { _varReqNumber = value; }
        }

        string _varServerName;

        /// <summary>
        /// Gets or sets the value of variable varServerName.
        /// </summary>
        [TestVariable("66e20567-ed45-4b19-875a-d9c0795ac480")]
        public string varServerName
        {
            get { return _varServerName; }
            set { _varServerName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CheckForUserReferenceinSP(varReqNumber, varServerName, ValueConverter.ArgumentFromString<int>("timeoutMinutes", "20"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
