///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MaintainShippingMethod recording.
    /// </summary>
    [TestModule("2ab4cc74-5472-4551-ac4e-6c806f813192", ModuleType.Recording, 1)]
    public partial class MaintainShippingMethod : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static MaintainShippingMethod instance = new MaintainShippingMethod();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MaintainShippingMethod()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MaintainShippingMethod Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SystemAdministration' at Center.", repo.MainWindow.NavigationPanel.SystemAdministrationInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.SystemAdministration.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SitePreferences' at Center.", repo.MainWindow.NavigationPanel.SitePreferencesInfo, new RecordItemIndex(1));
            repo.MainWindow.NavigationPanel.SitePreferences.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.AddRow' at Center.", repo.MainWindow.NavigationPanel.AddRowInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.AddRow.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.NewShippingMethodTextBox' at Center.", repo.MainWindow.NavigationPanel.NewShippingMethodTextBoxInfo, new RecordItemIndex(3));
            repo.MainWindow.NavigationPanel.NewShippingMethodTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'AP'.", new RecordItemIndex(4));
            Keyboard.Press("AP");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.NewDescriptionTextBox' at Center.", repo.MainWindow.NavigationPanel.NewDescriptionTextBoxInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.NewDescriptionTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Ranorex Created'.", new RecordItemIndex(6));
            Keyboard.Press("Ranorex Created");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.NewShippingDurationTextBox' at Center.", repo.MainWindow.NavigationPanel.NewShippingDurationTextBoxInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.NewShippingDurationTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}5'.", new RecordItemIndex(8));
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}{Delete}5");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.NewInactiveCheckBox' at Center.", repo.MainWindow.NavigationPanel.NewInactiveCheckBoxInfo, new RecordItemIndex(9));
            repo.MainWindow.NavigationPanel.NewInactiveCheckBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'NotificationsWindow.ShippingMethodError'", repo.NotificationsWindow.ShippingMethodErrorInfo, new ActionTimeout(60000), new RecordItemIndex(10));
            repo.NotificationsWindow.ShippingMethodErrorInfo.WaitForExists(60000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(11));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(12));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'NotificationsWindow.CloseButton' at Center.", repo.NotificationsWindow.CloseButtonInfo, new RecordItemIndex(13));
            repo.NotificationsWindow.CloseButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(14));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
