///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PrepareRequisition recording.
    /// </summary>
    [TestModule("c9254431-f1dd-41d3-a293-2bcb1f9274fe", ModuleType.Recording, 1)]
    public partial class PrepareRequisition : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static PrepareRequisition instance = new PrepareRequisition();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PrepareRequisition()
        {
            varReqNum = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PrepareRequisition Instance
        {
            get { return instance; }
        }

#region Variables

        string _varReqNum;

        /// <summary>
        /// Gets or sets the value of variable varReqNum.
        /// </summary>
        [TestVariable("d4b2be6b-e995-4667-83e0-07d7f1ce1854")]
        public string varReqNum
        {
            get { return _varReqNum; }
            set { _varReqNum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varReqNum = SPCollection.ReadReqFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RequisitionNumber\\req.txt");
            Delay.Milliseconds(0);
            
            SPCollection.EditJSONFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\JSON\\jsonSPOriginal.txt", "ANKIT999999ANKIT", varReqNum, "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\JSON\\jsonSP.txt");
            Delay.Milliseconds(0);
            
            SPCollection.EditJSONFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\JSON\\jsonSP.txt", "\"date_required\": \"2022-11-18\"", "\"date_required\": \"2027-08-11\"", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\JSON\\jsonSP.txt");
            Delay.Milliseconds(0);
            
            SPCollection.ActiveMQRequest("queue://ATSActiveMQJDEInboundSupplierPortal", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\JSON\\jsonSP.txt", "DEV", "00800");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
