///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitQuote recording.
    /// </summary>
    [TestModule("af95de18-1e0b-4953-96e7-e077de978f31", ModuleType.Recording, 1)]
    public partial class SubmitQuote : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SubmitQuote instance = new SubmitQuote();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitQuote()
        {
            varRFQNumber = "";
            varNumEntries = "";
            varRandom = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitQuote Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNumEntries;

        /// <summary>
        /// Gets or sets the value of variable varNumEntries.
        /// </summary>
        [TestVariable("b78f9627-79b0-434c-b7ce-5e636d32bab1")]
        public string varNumEntries
        {
            get { return _varNumEntries; }
            set { _varNumEntries = value; }
        }

        string _varRandom;

        /// <summary>
        /// Gets or sets the value of variable varRandom.
        /// </summary>
        [TestVariable("f146ad67-603e-4537-ae3d-6be2d0147c72")]
        public string varRandom
        {
            get { return _varRandom; }
            set { _varRandom = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("1a4ed82e-38a4-43bd-a158-cd54fafcc74a")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varRFQNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RFQNumber\\RFQNumber.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'LoginATSSupplierPortal.Search1'", repo.LoginATSSupplierPortal.Search1Info, new ActionTimeout(300000), new RecordItemIndex(1));
            repo.LoginATSSupplierPortal.Search1Info.WaitForExists(300000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to not exist. Associated repository item: 'RFQListingATSSupplierPortal.Loading'", repo.RFQListingATSSupplierPortal.LoadingInfo, new ActionTimeout(180000), new RecordItemIndex(2));
            repo.RFQListingATSSupplierPortal.LoadingInfo.WaitForNotExists(180000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Search' at Center.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(4));
            repo.LoginATSSupplierPortal.Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRFQNumber' with focus on 'LoginATSSupplierPortal.Search'.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(5));
            repo.LoginATSSupplierPortal.Search.PressKeys(varRFQNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.SelectRFQNumber' at Center.", repo.LoginATSSupplierPortal.SelectRFQNumberInfo, new RecordItemIndex(6));
            repo.LoginATSSupplierPortal.SelectRFQNumber.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'LoginATSSupplierPortal.BtnSetPromise'", repo.LoginATSSupplierPortal.BtnSetPromiseInfo, new ActionTimeout(10000), new RecordItemIndex(7));
            repo.LoginATSSupplierPortal.BtnSetPromiseInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.ATagFileAttachments' at Center.", repo.LoginATSSupplierPortal.ATagFileAttachmentsInfo, new RecordItemIndex(8));
            repo.LoginATSSupplierPortal.ATagFileAttachments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15s to exist. Associated repository item: 'LoginATSSupplierPortal.AttachmentPdf'", repo.LoginATSSupplierPortal.AttachmentPdfInfo, new ActionTimeout(15000), new RecordItemIndex(9));
            repo.LoginATSSupplierPortal.AttachmentPdfInfo.WaitForExists(15000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginATSSupplierPortal.AttachmentPdf'.", repo.LoginATSSupplierPortal.AttachmentPdfInfo, new RecordItemIndex(10));
            Validate.Exists(repo.LoginATSSupplierPortal.AttachmentPdfInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.AttachmentPdf' at Center.", repo.LoginATSSupplierPortal.AttachmentPdfInfo, new RecordItemIndex(11));
            repo.LoginATSSupplierPortal.AttachmentPdf.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'VendorQuoteATSSupplierPortalInt.Open' at Center.", repo.VendorQuoteATSSupplierPortalInt.OpenInfo, new RecordItemIndex(12));
            //repo.VendorQuoteATSSupplierPortalInt.Open.MoveTo();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VendorQuoteATSSupplierPortalInt.Open' at Center.", repo.VendorQuoteATSSupplierPortalInt.OpenInfo, new RecordItemIndex(13));
            //repo.VendorQuoteATSSupplierPortalInt.Open.Click();
            //Delay.Milliseconds(200);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'VendorQuoteATSSupplierPortalInt.Open' at Center.", repo.VendorQuoteATSSupplierPortalInt.OpenInfo, new RecordItemIndex(14));
                //repo.VendorQuoteATSSupplierPortalInt.Open.Click();
                //Delay.Milliseconds(200);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(14)); }
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(15));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}'.", new RecordItemIndex(16));
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Validate\\Attachment.pdf'.", new RecordItemIndex(17));
            Keyboard.Press("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Validate\\Attachment.pdf");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(18));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Validate\\Attachment.pdf' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(19));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\Validate\\Attachment.pdf");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(20));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at Center.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(21));
            repo.SaveAs.ButtonSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmSaveAs.ButtonYes' at Center.", repo.ConfirmSaveAs.ButtonYesInfo, new RecordItemIndex(22));
            repo.ConfirmSaveAs.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            OpenAttachment();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(24));
            Delay.Duration(2000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.AdobeReader.Self, false, new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(26));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'AdobeReader'.", repo.AdobeReader.SelfInfo, new RecordItemIndex(27));
            Host.Current.CloseApplication(repo.AdobeReader.Self, new Duration(0));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.FileInput' at Center.", repo.LoginATSSupplierPortal.FileInputInfo, new RecordItemIndex(28));
            repo.LoginATSSupplierPortal.FileInput.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\ATSDreamin.png' on item 'ChooseFileToUpload.Text1148'.", repo.ChooseFileToUpload.Text1148Info, new RecordItemIndex(29));
            repo.ChooseFileToUpload.Text1148.Element.SetAttributeValue("Text", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\FileAttachment\\ATSDreamin.png");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ChooseFileToUpload.ButtonOpen' at Center.", repo.ChooseFileToUpload.ButtonOpenInfo, new RecordItemIndex(30));
            repo.ChooseFileToUpload.ButtonOpen.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Attach' at Center.", repo.LoginATSSupplierPortal.AttachInfo, new RecordItemIndex(31));
            repo.LoginATSSupplierPortal.Attach.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(32));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s to exist. Associated repository item: 'LoginATSSupplierPortal.ATSDreaminPng'", repo.LoginATSSupplierPortal.ATSDreaminPngInfo, new ActionTimeout(10000), new RecordItemIndex(33));
            repo.LoginATSSupplierPortal.ATSDreaminPngInfo.WaitForExists(10000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'LoginATSSupplierPortal.ATSDreaminPng'.", repo.LoginATSSupplierPortal.ATSDreaminPngInfo, new RecordItemIndex(34));
            Validate.Exists(repo.LoginATSSupplierPortal.ATSDreaminPngInfo);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.MyAttachments' at Center.", repo.LoginATSSupplierPortal.MyAttachmentsInfo, new RecordItemIndex(35));
            repo.LoginATSSupplierPortal.MyAttachments.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(36));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            ClickPromiseDate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'LoginATSSupplierPortal.DetailsTableInfo' and assigning the part of its value captured by '\\d+(?!.*\\d+)' to variable 'varNumEntries'.", repo.LoginATSSupplierPortal.DetailsTableInfoInfo, new RecordItemIndex(38));
            varNumEntries = repo.LoginATSSupplierPortal.DetailsTableInfo.Element.GetAttributeValueText("InnerText", new Regex("\\d+(?!.*\\d+)"));
            Delay.Milliseconds(0);
            
            SPCollection.SetPriceinQuote(varNumEntries);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.VendorNote' at Center.", repo.LoginATSSupplierPortal.VendorNoteInfo, new RecordItemIndex(40));
            repo.LoginATSSupplierPortal.VendorNote.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to 'Random Note here' on item 'LoginATSSupplierPortal.VendorNote'.", repo.LoginATSSupplierPortal.VendorNoteInfo, new RecordItemIndex(41));
            repo.LoginATSSupplierPortal.VendorNote.Element.SetAttributeValue("InnerText", "Random Note here");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(42));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSetPromise' at Center.", repo.LoginATSSupplierPortal.BtnSetPromiseInfo, new RecordItemIndex(43));
            repo.LoginATSSupplierPortal.BtnSetPromise.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(44));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(45));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(46));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            varRandom = SPCollection.RandomString(ValueConverter.ArgumentFromString<int>("length", "8"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.QuoteNumber' at Center.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(48));
            repo.LoginATSSupplierPortal.QuoteNumber.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varRandom' on item 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(49));
            //repo.LoginATSSupplierPortal.QuoteNumber.Element.SetAttributeValue("InnerText", varRandom);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRandom' with focus on 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(50));
            repo.LoginATSSupplierPortal.QuoteNumber.PressKeys(varRandom);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSave' at Center.", repo.LoginATSSupplierPortal.BtnSaveInfo, new RecordItemIndex(51));
            repo.LoginATSSupplierPortal.BtnSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(52));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            SPCollection.GetUnitPrices(varNumEntries);
            Delay.Milliseconds(0);
            
            //SPCollection.GetUnitPrices("6");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(55));
            repo.LoginATSSupplierPortal.BtnSubmit.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(56));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}'.", new RecordItemIndex(57));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{Right}{Right}{Right}'.", new RecordItemIndex(58));
            Keyboard.Press("{Right}{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            ClickButtonSubmit();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(60));
            //repo.LoginATSSupplierPortal.BtnSubmit.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(61));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.LoginATSSupplierPortal.Self, false, new RecordItemIndex(62));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
