///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateOrderNumberJDEPROD recording.
    /// </summary>
    [TestModule("4f5a08fb-6668-42ea-bca8-77645ce32a0d", ModuleType.Recording, 1)]
    public partial class ValidateOrderNumberJDEPROD : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ValidateOrderNumberJDEPROD instance = new ValidateOrderNumberJDEPROD();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateOrderNumberJDEPROD()
        {
            varJDEOrderNumber = "";
            varRFQNumber = "";
            varNumRecords = "2";
            varUserReferenceNumber = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateOrderNumberJDEPROD Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNumRecords;

        /// <summary>
        /// Gets or sets the value of variable varNumRecords.
        /// </summary>
        [TestVariable("19101327-e412-4d49-876f-2c03cbe5bc5f")]
        public string varNumRecords
        {
            get { return _varNumRecords; }
            set { _varNumRecords = value; }
        }

        string _varUserReferenceNumber;

        /// <summary>
        /// Gets or sets the value of variable varUserReferenceNumber.
        /// </summary>
        [TestVariable("dafbd2a7-6fe0-433e-8915-df99a81be0ab")]
        public string varUserReferenceNumber
        {
            get { return _varUserReferenceNumber; }
            set { _varUserReferenceNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varJDEOrderNumber.
        /// </summary>
        [TestVariable("1af8eed1-8ad4-4585-836f-0e0cf77f8dbb")]
        public string varJDEOrderNumber
        {
            get { return repo.varJDEOrderNumber; }
            set { repo.varJDEOrderNumber = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("cc2b08ca-e489-44f4-8a64-d0183e4158e9")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            varJDEOrderNumber = SPCollection.SQLJDEPRODReturnOrderNumber(varRFQNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varJDEOrderNumber, new RecordItemIndex(1));
            
            varUserReferenceNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RequisitionNumber\\req.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(3));
            repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(4));
            repo.JDEPath.InputTag013.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varJDEOrderNumber' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(5));
            repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", varJDEOrderNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'JDEPath.UserReferenceTextBox'.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(6));
            repo.JDEPath.UserReferenceTextBox.Element.SetAttributeValue("InnerText", "");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.UserReferenceTextBox' at Center.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(7));
            repo.JDEPath.UserReferenceTextBox.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varUserReferenceNumber' with focus on 'JDEPath.UserReferenceTextBox'.", repo.JDEPath.UserReferenceTextBoxInfo, new RecordItemIndex(8));
            repo.JDEPath.UserReferenceTextBox.PressKeys(varUserReferenceNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(9));
            repo.JDEPath.Find.Click();
            Delay.Milliseconds(200);
            
            // Validating Last Status
            Report.Log(ReportLevel.Info, "Validation", "Validating Last Status\r\nValidating AttributeEqual (InnerText='230') on item 'JDEPath.JdeGridData010.LastStatusRow0'.", repo.JDEPath.JdeGridData010.LastStatusRow0Info, new RecordItemIndex(10));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.LastStatusRow0Info, "InnerText", "230");
            Delay.Milliseconds(0);
            
            // Validating Next Status
            Report.Log(ReportLevel.Info, "Validation", "Validating Next Status\r\nValidating AttributeEqual (InnerText='280') on item 'JDEPath.JdeGridData010.NextStatusRow0'.", repo.JDEPath.JdeGridData010.NextStatusRow0Info, new RecordItemIndex(11));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.NextStatusRow0Info, "InnerText", "280");
            Delay.Milliseconds(0);
            
            // Validating Buyer Number for User RanorexRT
            Report.Log(ReportLevel.Info, "Validation", "Validating Buyer Number for User RanorexRT\r\nValidating AttributeEqual (InnerText='192257') on item 'JDEPath.JdeGridData010.BuyerNumberRow0'.", repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, new RecordItemIndex(12));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.BuyerNumberRow0Info, "InnerText", "192257");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='ON') on item 'JDEPath.JdeGridData010.OrderTypeRow0'.", repo.JDEPath.JdeGridData010.OrderTypeRow0Info, new RecordItemIndex(13));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.OrderTypeRow0Info, "InnerText", "ON");
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
