///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfirmReportCode3 recording.
    /// </summary>
    [TestModule("e16e3941-2961-4101-a7af-a9196b681399", ModuleType.Recording, 1)]
    public partial class ConfirmReportCode3 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ConfirmReportCode3 instance = new ConfirmReportCode3();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfirmReportCode3()
        {
            varNumRecords = "2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfirmReportCode3 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNumRecords;

        /// <summary>
        /// Gets or sets the value of variable varNumRecords.
        /// </summary>
        [TestVariable("5a22f675-64dc-415e-b373-f789d2b7057d")]
        public string varNumRecords
        {
            get { return _varNumRecords; }
            set { _varNumRecords = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.NumRecords' and assigning the part of its value captured by '\\d+(?!.*\\d+)' to variable 'varNumRecords'.", repo.JDEPath.NumRecordsInfo, new RecordItemIndex(0));
            varNumRecords = repo.JDEPath.NumRecords.Element.GetAttributeValueText("InnerText", new Regex("\\d+(?!.*\\d+)"));
            Delay.Milliseconds(0);
            
            SPCollection.ConfirmPOJDE(varNumRecords);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(2));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
