///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateShippingChangesJDE recording.
    /// </summary>
    [TestModule("6f91a427-ac41-4064-9fa4-ec9b666625f3", ModuleType.Recording, 1)]
    public partial class ValidateShippingChangesJDE : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ValidateShippingChangesJDE instance = new ValidateShippingChangesJDE();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateShippingChangesJDE()
        {
            varJDEOrderNumber = "";
            varLineNumber = "";
            varConvertedLineNo = "";
            varTrackingNo = "";
            varExFactoryDateMMDDYYYY = "";
            varExFactoryDate = "";
            varJDETrackingNoValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateShippingChangesJDE Instance
        {
            get { return instance; }
        }

#region Variables

        string _varLineNumber;

        /// <summary>
        /// Gets or sets the value of variable varLineNumber.
        /// </summary>
        [TestVariable("7f590514-3059-4d30-a410-6e5ea3a3794e")]
        public string varLineNumber
        {
            get { return _varLineNumber; }
            set { _varLineNumber = value; }
        }

        string _varConvertedLineNo;

        /// <summary>
        /// Gets or sets the value of variable varConvertedLineNo.
        /// </summary>
        [TestVariable("814b2cf1-8968-49ff-8b77-438c955581a0")]
        public string varConvertedLineNo
        {
            get { return _varConvertedLineNo; }
            set { _varConvertedLineNo = value; }
        }

        string _varTrackingNo;

        /// <summary>
        /// Gets or sets the value of variable varTrackingNo.
        /// </summary>
        [TestVariable("9a2a2b51-297b-47b3-aa37-85e77c96201b")]
        public string varTrackingNo
        {
            get { return _varTrackingNo; }
            set { _varTrackingNo = value; }
        }

        string _varExFactoryDateMMDDYYYY;

        /// <summary>
        /// Gets or sets the value of variable varExFactoryDateMMDDYYYY.
        /// </summary>
        [TestVariable("d8529006-8b95-44e8-bd9a-dfb6dd4d3424")]
        public string varExFactoryDateMMDDYYYY
        {
            get { return _varExFactoryDateMMDDYYYY; }
            set { _varExFactoryDateMMDDYYYY = value; }
        }

        string _varExFactoryDate;

        /// <summary>
        /// Gets or sets the value of variable varExFactoryDate.
        /// </summary>
        [TestVariable("ff6514f1-67ee-42ee-9a36-db4f6671a8ff")]
        public string varExFactoryDate
        {
            get { return _varExFactoryDate; }
            set { _varExFactoryDate = value; }
        }

        string _varJDETrackingNoValue;

        /// <summary>
        /// Gets or sets the value of variable varJDETrackingNoValue.
        /// </summary>
        [TestVariable("5a9bf2c8-7d1b-46df-b2d8-2541b658fa4b")]
        public string varJDETrackingNoValue
        {
            get { return _varJDETrackingNoValue; }
            set { _varJDETrackingNoValue = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varJDEOrderNumber.
        /// </summary>
        [TestVariable("dc7f25be-d5e6-44b1-b5ca-5bd8fbefdc06")]
        public string varJDEOrderNumber
        {
            get { return repo.varJDEOrderNumber; }
            set { repo.varJDEOrderNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.PurchasingGeneral' at Center.", repo.JDEPath.PurchasingGeneralInfo, new RecordItemIndex(0));
            repo.JDEPath.PurchasingGeneral.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.ViewAllDocTypes' at Center.", repo.JDEPath.ViewAllDocTypesInfo, new RecordItemIndex(1));
            repo.JDEPath.ViewAllDocTypes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'JDEPath.InputTag013'", repo.JDEPath.InputTag013Info, new ActionTimeout(30000), new RecordItemIndex(2));
            repo.JDEPath.InputTag013Info.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(3));
            repo.JDEPath.InputTag013.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}' with focus on 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(4));
            repo.JDEPath.InputTag013.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(5));
            repo.JDEPath.InputTag013.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varJDEOrderNumber'.", new RecordItemIndex(6));
            Keyboard.Press(varJDEOrderNumber);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(7));
            //repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", "");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.InputTag013' at Center.", repo.JDEPath.InputTag013Info, new RecordItemIndex(8));
            //repo.JDEPath.InputTag013.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varJDEOrderNumber' on item 'JDEPath.InputTag013'.", repo.JDEPath.InputTag013Info, new RecordItemIndex(9));
            //repo.JDEPath.InputTag013.Element.SetAttributeValue("InnerText", varJDEOrderNumber);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.Find' at Center.", repo.JDEPath.FindInfo, new RecordItemIndex(10));
            repo.JDEPath.Find.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 10s.", new RecordItemIndex(11));
            Delay.Duration(10000, false);
            
            varConvertedLineNo = ConvertLineNumber(varLineNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.LineNumberHeader' at Center.", repo.JDEPath.LineNumberHeaderInfo, new RecordItemIndex(13));
            repo.JDEPath.LineNumberHeader.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varConvertedLineNo'.", new RecordItemIndex(14));
            Keyboard.Press(varConvertedLineNo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}'.", new RecordItemIndex(15));
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(16));
            Delay.Duration(5000, false);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(17));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='GND') on item 'JDEPath.JdeGridData010.ShippingMethod'.", repo.JDEPath.JdeGridData010.ShippingMethodInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.ShippingMethodInfo, "InnerText", "GND");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'JDEPath.JdeGridData010.TrackingNo' and assigning its value to variable 'varJDETrackingNoValue'.", repo.JDEPath.JdeGridData010.TrackingNoInfo, new RecordItemIndex(19));
            varJDETrackingNoValue = repo.JDEPath.JdeGridData010.TrackingNo.Element.GetAttributeValueText("InnerText");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", varJDETrackingNoValue, new RecordItemIndex(20));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varTrackingNo) on item 'JDEPath.JdeGridData010.TrackingNo'.", repo.JDEPath.JdeGridData010.TrackingNoInfo, new RecordItemIndex(21));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.TrackingNoInfo, "InnerText", varTrackingNo);
            Delay.Milliseconds(0);
            
            varExFactoryDate = ConvertExFactoryDate(varExFactoryDateMMDDYYYY);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varExFactoryDate) on item 'JDEPath.JdeGridData010.ExFactoryDate'.", repo.JDEPath.JdeGridData010.ExFactoryDateInfo, new RecordItemIndex(23));
            Validate.AttributeEqual(repo.JDEPath.JdeGridData010.ExFactoryDateInfo, "InnerText", varExFactoryDate);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'JDEPath.JdeGridData010.TrackingNo' at Center.", repo.JDEPath.JdeGridData010.TrackingNoInfo, new RecordItemIndex(24));
            repo.JDEPath.JdeGridData010.TrackingNo.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.JDEPath.Self, false, new RecordItemIndex(25));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
