///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SubmitQuote2 recording.
    /// </summary>
    [TestModule("d2626839-7e70-46c4-9b4c-cf63a3186116", ModuleType.Recording, 1)]
    public partial class SubmitQuote2 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SubmitQuote2 instance = new SubmitQuote2();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SubmitQuote2()
        {
            varRFQNumber = "";
            varNumEntries = "";
            varRandom = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SubmitQuote2 Instance
        {
            get { return instance; }
        }

#region Variables

        string _varNumEntries;

        /// <summary>
        /// Gets or sets the value of variable varNumEntries.
        /// </summary>
        [TestVariable("5b07ac98-8043-4292-a969-a0de10ed6053")]
        public string varNumEntries
        {
            get { return _varNumEntries; }
            set { _varNumEntries = value; }
        }

        string _varRandom;

        /// <summary>
        /// Gets or sets the value of variable varRandom.
        /// </summary>
        [TestVariable("96823718-874a-4be5-b13c-230f5df466ea")]
        public string varRandom
        {
            get { return _varRandom; }
            set { _varRandom = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("a4d8b109-2a79-46d1-98cc-e8cc86072647")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(0));
            Delay.Duration(5000, false);
            
            varRFQNumber = SPCollection.ReadRequisitionFile("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\RFQNumber\\RFQNumber.txt");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5m to exist. Associated repository item: 'LoginATSSupplierPortal.Search1'", repo.LoginATSSupplierPortal.Search1Info, new ActionTimeout(300000), new RecordItemIndex(2));
            repo.LoginATSSupplierPortal.Search1Info.WaitForExists(300000);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 3m to not exist. Associated repository item: 'RFQListingATSSupplierPortal.Loading'", repo.RFQListingATSSupplierPortal.LoadingInfo, new ActionTimeout(180000), new RecordItemIndex(3));
            repo.RFQListingATSSupplierPortal.LoadingInfo.WaitForNotExists(180000);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.Search' at Center.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(5));
            repo.LoginATSSupplierPortal.Search.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRFQNumber' with focus on 'LoginATSSupplierPortal.Search'.", repo.LoginATSSupplierPortal.SearchInfo, new RecordItemIndex(6));
            repo.LoginATSSupplierPortal.Search.PressKeys(varRFQNumber);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.SelectRFQNumber' at Center.", repo.LoginATSSupplierPortal.SelectRFQNumberInfo, new RecordItemIndex(7));
            repo.LoginATSSupplierPortal.SelectRFQNumber.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(8));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.SelectRFQNumber' at Center.", repo.LoginATSSupplierPortal.SelectRFQNumberInfo, new RecordItemIndex(9));
            repo.LoginATSSupplierPortal.SelectRFQNumber.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.BtnSetPromise'", repo.LoginATSSupplierPortal.BtnSetPromiseInfo, new ActionTimeout(30000), new RecordItemIndex(10));
            repo.LoginATSSupplierPortal.BtnSetPromiseInfo.WaitForExists(30000);
            
            ClickPromiseDate();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'LoginATSSupplierPortal.DetailsTableInfo' and assigning the part of its value captured by '\\d+(?!.*\\d+)' to variable 'varNumEntries'.", repo.LoginATSSupplierPortal.DetailsTableInfoInfo, new RecordItemIndex(12));
            varNumEntries = repo.LoginATSSupplierPortal.DetailsTableInfo.Element.GetAttributeValueText("InnerText", new Regex("\\d+(?!.*\\d+)"));
            Delay.Milliseconds(0);
            
            SetPrices(varNumEntries);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.VendorNote' at Center.", repo.LoginATSSupplierPortal.VendorNoteInfo, new RecordItemIndex(14));
            repo.LoginATSSupplierPortal.VendorNote.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Random Note here' with focus on 'LoginATSSupplierPortal.VendorNote'.", repo.LoginATSSupplierPortal.VendorNoteInfo, new RecordItemIndex(15));
            repo.LoginATSSupplierPortal.VendorNote.PressKeys("Random Note here");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to 'Random Note here' on item 'LoginATSSupplierPortal.VendorNote'.", repo.LoginATSSupplierPortal.VendorNoteInfo, new RecordItemIndex(16));
            //repo.LoginATSSupplierPortal.VendorNote.Element.SetAttributeValue("InnerText", "Random Note here");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSetPromise' at Center.", repo.LoginATSSupplierPortal.BtnSetPromiseInfo, new RecordItemIndex(17));
            repo.LoginATSSupplierPortal.BtnSetPromise.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(18));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(19));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}'.", new RecordItemIndex(20));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}");
            Delay.Milliseconds(0);
            
            varRandom = SPCollection.RandomString(ValueConverter.ArgumentFromString<int>("length", "8"));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.QuoteNumber' at Center.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(22));
            repo.LoginATSSupplierPortal.QuoteNumber.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute InnerText to '$varRandom' on item 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(23));
            //repo.LoginATSSupplierPortal.QuoteNumber.Element.SetAttributeValue("InnerText", varRandom);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varRandom' with focus on 'LoginATSSupplierPortal.QuoteNumber'.", repo.LoginATSSupplierPortal.QuoteNumberInfo, new RecordItemIndex(24));
            repo.LoginATSSupplierPortal.QuoteNumber.PressKeys(varRandom);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSave' at Center.", repo.LoginATSSupplierPortal.BtnSaveInfo, new RecordItemIndex(25));
            repo.LoginATSSupplierPortal.BtnSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(26));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(27));
            repo.LoginATSSupplierPortal.BtnSubmit.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(28));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}'.", new RecordItemIndex(29));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            ClickButtonSubmit();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnSubmit' at Center.", repo.LoginATSSupplierPortal.BtnSubmitInfo, new RecordItemIndex(31));
            //repo.LoginATSSupplierPortal.BtnSubmit.Click();
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'LoginATSSupplierPortal.LblNotify'", repo.LoginATSSupplierPortal.LblNotifyInfo, new ActionTimeout(30000), new RecordItemIndex(32));
            repo.LoginATSSupplierPortal.LblNotifyInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.LoginATSSupplierPortal.Self, false, new RecordItemIndex(33));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
