///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The OpenSupplierPortal recording.
    /// </summary>
    [TestModule("85fa9c53-4bec-4a8e-ad55-18292902a4cd", ModuleType.Recording, 1)]
    public partial class OpenSupplierPortal : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static OpenSupplierPortal instance = new OpenSupplierPortal();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public OpenSupplierPortal()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static OpenSupplierPortal Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application '\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Supplier Portal\\Resources\\start.vbs' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Supplier Portal\\Resources\\start.vbs", "", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\ATS Supplier Portal\\Resources", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1.5m to exist. Associated repository item: 'MainWindow'", repo.MainWindow.SelfInfo, new ActionTimeout(90000), new RecordItemIndex(1));
            repo.MainWindow.SelfInfo.WaitForExists(90000);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Maximize() on item 'MainWindow'.", repo.MainWindow.SelfInfo, new RecordItemIndex(2));
            repo.MainWindow.Self.Maximize();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
