///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ExportRFQPROD recording.
    /// </summary>
    [TestModule("b2a1dc65-7843-4f13-84b8-9d240f001924", ModuleType.Recording, 1)]
    public partial class ExportRFQPROD : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static ExportRFQPROD instance = new ExportRFQPROD();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ExportRFQPROD()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ExportRFQPROD Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.CurrencyTag' at Center.", repo.LoginATSSupplierPortal.CurrencyTagInfo, new RecordItemIndex(1));
            repo.LoginATSSupplierPortal.CurrencyTag.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}'.", new RecordItemIndex(2));
            Keyboard.Press("{PageUp}{PageUp}{PageUp}{Right}{Right}{Right}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'LoginATSSupplierPortal.BtnExport' at Center.", repo.LoginATSSupplierPortal.BtnExportInfo, new RecordItemIndex(3));
            repo.LoginATSSupplierPortal.BtnExport.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(4));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Delete}'.", new RecordItemIndex(5));
            Keyboard.Press("{LControlKey down}{Akey}{LControlKey up}{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RFQExport\\RFQExport.xlsx'.", new RecordItemIndex(6));
            Keyboard.Press("\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RFQExport\\RFQExport.xlsx");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.FileName' at Center.", repo.SaveAs.FileNameInfo, new RecordItemIndex(7));
            repo.SaveAs.FileName.Click();
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'VendorQuoteATSSupplierPortalInt.Options' at Center.", repo.VendorQuoteATSSupplierPortalInt.OptionsInfo, new RecordItemIndex(8));
            //repo.VendorQuoteATSSupplierPortalInt.Options.MoveTo();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(9));
            //Delay.Duration(2000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VendorQuoteATSSupplierPortalInt.Options' at Center.", repo.VendorQuoteATSSupplierPortalInt.OptionsInfo, new RecordItemIndex(10));
            //repo.VendorQuoteATSSupplierPortalInt.Options.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Iexplore.SaveAs' at Center.", repo.Iexplore.SaveAsInfo, new RecordItemIndex(11));
            //repo.Iexplore.SaveAs.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(12));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RFQExport\\RFQExport.xlsx' on item 'SaveAs.FileName'.", repo.SaveAs.FileNameInfo, new RecordItemIndex(13));
            //repo.SaveAs.FileName.Element.SetAttributeValue("Text", "\\\\ca01a9001\\pgmis\\Deployment_DEV\\Ranorex\\Supplier_Portal\\PROD\\RFQExport\\RFQExport.xlsx");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SaveAs.ButtonSave' at Center.", repo.SaveAs.ButtonSaveInfo, new RecordItemIndex(14));
            repo.SaveAs.ButtonSave.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConfirmSaveAs.ButtonYes' at Center.", repo.ConfirmSaveAs.ButtonYesInfo, new RecordItemIndex(15));
            repo.ConfirmSaveAs.ButtonYes.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'VendorQuoteATSSupplierPortalInt.Close' at Center.", repo.VendorQuoteATSSupplierPortalInt.CloseInfo, new RecordItemIndex(16));
            repo.VendorQuoteATSSupplierPortalInt.Close.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
