///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CleanupSupplierPortalPROD recording.
    /// </summary>
    [TestModule("ee11b6f9-aa0e-4197-96c5-8a471a1db43d", ModuleType.Recording, 1)]
    public partial class CleanupSupplierPortalPROD : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static CleanupSupplierPortalPROD instance = new CleanupSupplierPortalPROD();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CleanupSupplierPortalPROD()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CleanupSupplierPortalPROD Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            SPCollection.SQLCleanupSPPROD("DELETE tblDetailCost WHERE VendorQuoteID IN (SELECT VendorQuoteID FROM tblVendorQuote WHERE RFQID IN (SELECT DISTINCT RFQID FROM tblDetail WHERE CompanyCode = '00630'))", "Deleting Detail Cost");
            Delay.Milliseconds(0);
            
            SPCollection.SQLCleanupSPPROD("DELETE tblVendorQuote WHERE RFQID IN (SELECT DISTINCT RFQID FROM tblDetail WHERE CompanyCode = '00630')", "Deleting Vendor Quote");
            Delay.Milliseconds(0);
            
            SPCollection.SQLCleanupSPPROD("DELETE tblRFQHistory WHERE RFQID IN ( SELECT DISTINCT RFQID FROM tblDetail WHERE CompanyCode = '00630')", "Deleting Table RFQ History");
            Delay.Milliseconds(0);
            
            SPCollection.SQLCleanupSPPROD("DELETE tblRFQ WHERE RFQID IN ( SELECT DISTINCT RFQID FROM tblDetail WHERE CompanyCode = '00630')", "Deleting RFQ");
            Delay.Milliseconds(0);
            
            SPCollection.SQLCleanupSPPROD("DELETE tblDetail WHERE CompanyCode = '00630'", "Deleting Details");
            Delay.Milliseconds(0);
            
            SPCollection.SQLCleanupSPPROD("DELETE tblPoChanges WHERE PDKCOO = '00630'", "Deleting PO Changes");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
