///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ATS_Supplier_Portal_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectWinner recording.
    /// </summary>
    [TestModule("072a405b-a852-4113-bd3d-7ca79d9b5a30", ModuleType.Recording, 1)]
    public partial class SelectWinner : ITestModule
    {
        /// <summary>
        /// Holds an instance of the ATS_Supplier_Portal_TestRepository repository.
        /// </summary>
        public static ATS_Supplier_Portal_TestRepository repo = ATS_Supplier_Portal_TestRepository.Instance;

        static SelectWinner instance = new SelectWinner();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectWinner()
        {
            varCellName = "";
            varColumnName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectWinner Instance
        {
            get { return instance; }
        }

#region Variables

        string _varCellName;

        /// <summary>
        /// Gets or sets the value of variable varCellName.
        /// </summary>
        [TestVariable("fc9cf44d-b818-4278-bcd6-97fc3bd2675f")]
        public string varCellName
        {
            get { return _varCellName; }
            set { _varCellName = value; }
        }

        string _varColumnName;

        /// <summary>
        /// Gets or sets the value of variable varColumnName.
        /// </summary>
        [TestVariable("9046a54a-13c3-43e1-a728-697266115f82")]
        public string varColumnName
        {
            get { return _varColumnName; }
            set { _varColumnName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable varRFQNumber.
        /// </summary>
        [TestVariable("2a5658e7-dbcd-408c-b807-d7a6ed6f73ba")]
        public string varRFQNumber
        {
            get { return repo.varRFQNumber; }
            set { repo.varRFQNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.ProcessRFQButton' at Center.", repo.MainWindow.NavigationPanel.ProcessRFQButtonInfo, new RecordItemIndex(0));
            repo.MainWindow.NavigationPanel.ProcessRFQButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 5s.", new RecordItemIndex(1));
            Delay.Duration(5000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'MainWindow.NavigationPanel.DetailViewDropDown' at Center.", repo.MainWindow.NavigationPanel.DetailViewDropDownInfo, new RecordItemIndex(2));
            repo.MainWindow.NavigationPanel.DetailViewDropDown.MoveTo();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.DetailViewDropDown' at Center.", repo.MainWindow.NavigationPanel.DetailViewDropDownInfo, new RecordItemIndex(3));
            repo.MainWindow.NavigationPanel.DetailViewDropDown.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ATSSupplierPortalManagment.All' at Center.", repo.ATSSupplierPortalManagment.AllInfo, new RecordItemIndex(4));
            repo.ATSSupplierPortalManagment.All.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SelectRFQ' at Center.", repo.MainWindow.NavigationPanel.SelectRFQInfo, new RecordItemIndex(5));
            repo.MainWindow.NavigationPanel.SelectRFQ.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'MainWindow.BusyOverlay'", repo.MainWindow.BusyOverlayInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.MainWindow.BusyOverlayInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.Vendors' at Center.", repo.MainWindow.NavigationPanel.VendorsInfo, new RecordItemIndex(7));
            repo.MainWindow.NavigationPanel.Vendors.Click();
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(8));
            
            ClickCellName(varCellName, varColumnName);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MainWindow.NavigationPanel.SelectWinner' at Center.", repo.MainWindow.NavigationPanel.SelectWinnerInfo, new RecordItemIndex(10));
            repo.MainWindow.NavigationPanel.SelectWinner.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'NotificationsWindow.WinnerHasBeenSelected'", repo.NotificationsWindow.WinnerHasBeenSelectedInfo, new ActionTimeout(30000), new RecordItemIndex(11));
            repo.NotificationsWindow.WinnerHasBeenSelectedInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'NotificationsWindow.WinnerHasBeenSelected'.", repo.NotificationsWindow.WinnerHasBeenSelectedInfo, new RecordItemIndex(12));
            Validate.Exists(repo.NotificationsWindow.WinnerHasBeenSelectedInfo);
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "", repo.MainWindow.Self, false, new RecordItemIndex(13));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
